### PR TITLE
fix store bug with non json values

### LINKED ISSUE #1115: Atmos 1.165.1 breaks functionality of atmos describe component
### Describe the Bug

After updating to Atmos 1.165.1, I started seeing errors on some components when running `atmos describe component <component_name> -s dev --format=json --process-templates=true`.  If I run on 1.165.0 I don't see any issues. The full error message I see is:

`ERRO failed to get key: failed to unmarshal parameter value: invalid character '/' looking for beginning of value`

The invalid character changes depending on the component and includes other letters as well. 

### Expected Behavior

The expected behavior is to get the correct JSON (or other format) output after running the command. 

### Steps to Reproduce

Starting on version 1.165.0 of Atmos, run the above command. This should work as expected for all components. Then upgrade to 1.165.1 and run the same command and the error begins. This does not happen on all of our components, but probably 75% of them. I cannot determine what is different between the working ones vs. the broken ones though. 

### Screenshots

_No response_

### Environment

- OS - macOS Sequoia v15.3.1
- Terraform version - 1.10.5
- Atmos version 1.165.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mcalhoun**
## what

- In the SSM and Redis stores, try to unmarshall the value from JSON first, and if that fails, return the raw value.
- Fix linting errors that existed in this package prior to this change

## why

Before this change, atmos was expecting that all values in the store are JSON stringified, as we introduced this functionality to support objects, lists and maps being stored. 

However, if the value was set with a version of atmos prior to our introducing the JSON stringification, then the value in the store is still the "raw" value, without being stringified. It is also possible that a 3rd party process (other than atmos) has set these values and we are just consuming them. This change allows atmos to support both cases.

## references

Closes #1115 

## Summary by CodeRabbit

- **Bug Fixes & Improvements**
  - Enhanced error handling across various store implementations, providing more specific error messages and improving overall reliability in parameter retrieval.
  - Streamlined control flow in methods to return raw data when structured parsing fails, enhancing flexibility in handling parameter values.

- **Tests**
  - Expanded test coverage to ensure retrieval methods handle diverse value formats—including plain text, malformed data, and numeric inputs—accurately.

- **Chores**
  - Refined build workflows and code formatting for improved consistency and maintainability.

### CODE REVIEW

File: pkg/store/artifactory_store.go [hunk 1]
```diff
@@ -112,35 +116,59 @@ func NewArtifactoryStore(options ArtifactoryStoreOptions) (Store, error) {
...
 
 	if key == "" {
-		return nil, fmt.Errorf("key cannot be empty")
+		return ErrEmptyKey
+	}
+
+	return nil
+}
+
+func (s *ArtifactoryStore) processDownloadedFile(tempDir, paramName string) (interface{}, error) {
```
Comment (osterman) [inline pkg/store/artifactory_store.go:144]: @mcalhoun we can remove `gofmt` from the `.golangci-lint.yaml` config, because it's not identical to `gofumpt`

**Review by osterman — APPROVED** [review]
