### PR TITLE
fix: base path resolution for ATMOS_BASE_PATH and --base-path with relative paths

### LINKED ISSUE #2183: Error: failed to find import
### Describe the Bug

When running `atmos describe affected` or `atmos tf plan --affected` it fails:
```
$ atmos describe affected

   Error 

   Error: failed to find import
$ atmos tf plan --affected

   Error 

   Error: failed to find import
```

### Expected Behavior

If running `atmos tf plan --affected`, the expectation is to only plan components that have been changed based on git commits

### Steps to Reproduce

```
$ atmos describe affected

   Error 

   Error: failed to find import
$ atmos tf plan --affected

   Error 

   Error: failed to find import
```
It also happens when using https://atmos.tools/integrations/github-actions/affected-stacks
```
  eval "atmos describe affected --file affected-stacks.json --include-settings=false --repo-path "/opt/actions-runner/_work/iac-gh-repos/iac-gh-repos/base-ref""
  affected=$(jq -c '.' affected-stacks.json)
  printf "%s" "affected=$affected" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ATMOS_CLI_CONFIG_PATH: /opt/actions-runner/_work/iac-gh-repos/iac-gh-repos/.atmos.yaml
# Error

**Error:** failed to find import
```

### Screenshots

_No response_

### Environment

- OS: Ubuntu-24.04
- Version: v1.209.0
- Module: N/A
- Terraform: v1.11.4

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aknysh**
## what

- Fix `failed to find import` error when `ATMOS_BASE_PATH` env var (or `--base-path` flag / `atmos_base_path` provider parameter) is set to a relative path like `.terraform/modules/monorepo`
- Fix `failed to find import` error in `atmos describe affected` caused by git root discovery interfering with configured `base_path`
- Improve `failed to find import` error messages with actionable hints and context (pattern, stacks base path)
- Formalize base path resolution semantics with 4-category classification and source-dependent anchoring

## why

Since v1.202.0, `resolveAbsolutePath()` routes simple relative paths through git root discovery. This breaks two scenarios:

**Scenario 1: `terraform-provider-utils` with `ATMOS_BASE_PATH` env var**

When a user sets `ATMOS_BASE_PATH=.terraform/modules/monorepo` on a CI/CD worker (e.g., Spacelift), the path should resolve relative to CWD (`/project/components/terraform/iam-delegated-roles/.terraform/modules/monorepo`). Instead, git root discovery resolves it to `/project/.terraform/modules/monorepo` — a path that doesn't exist — causing `failed to find import`.

**Scenario 2: `atmos describe affected`**

In CI environments where the working directory structure differs from expectations, git root discovery can compute the stacks base path incorrectly, causing stack processing to fail with `failed to find import`.

**Error message problem**

The bare `failed to find import` error provides no context about which import failed or what path was searched, making it impossible for users to diagnose.

### Fix approach

**Fix 1: Source-aware base path resolution**

Every `base_path` value is classified into one of four categories:

| Category | Pattern | Resolution |
|----------|---------|------------|
| **Empty** | `""`, unset | Git root → config dir → CWD (smart default) |
| **Dot** | `"."`, `"./foo"`, `".."`, `"../foo"` | Source-dependent anchor (see below) |
| **Bare** | `"foo"`, `"foo/bar"`, `".terraform/..."` | Git root search, source-independent |
| **Absolute** | `"/abs/path"` | Pass through unchanged |

A `BasePathSource` field on `AtmosConfiguration` tracks whether the base path came from a runtime source or config file:

- **Runtime sources** (env var `ATMOS_BASE_PATH`, CLI flag `--base-path`, provider param `atmos_base_path`): set `BasePathSource = "runtime"`. Dot-prefixed paths resolve relative to **CWD** (shell convention).
- **Config source** (`base_path` in `atmos.yaml`): dot-prefixed paths resolve relative to the **directory containing `atmos.yaml`** (config-file convention).
- **Bare paths** are source-independent — they always go through git root search regardless of where they were specified.

`resolveAbsolutePath()` now accepts a `source` parameter and routes dot-prefixed paths through `resolveDotPrefixPath()`. The `tryResolveWithGitRoot()` function adds `os.Stat` validation — if the git-root-joined path doesn't exist but the CWD-relative path does, it falls back to the CWD-relative path.

**Fix 2: Actionable error messages**

Wrap `ErrFailedToFindImport` with the error builder pattern in `FindAllStackConfigsInPathsForStack`, `FindAllStackConfigsInPaths`, and `GetGlobMatches`, adding hints about checking `base_path`, `stacks.base_path`, and `ATMOS_BASE_PATH`. All path resolution errors use `errUtils.Build(errUtils.ErrPathResolution)` for consistent `errors.Is()` classification.

### Spacelift/provider scenario

`ATMOS_BASE_PATH=./.terraform/modules/monorepo` (recommended dot-slash form): classified as Dot, runtime source → resolves relative to CWD. Works correctly.

`ATMOS_BASE_PATH=.terraform/modules/monorepo` (existing bare form): classified as Bare, goes through git root search → `os.Stat` at git root fails → falls back to CWD. Also works correctly.

### Git root discovery compatibility

The "run Atmos from any subdirectory" feature (v1.202.0+) is **not affected**:
- Source-aware resolution only changes behavior for dot-prefixed paths from runtime sources
- Bare paths (`"stacks"`, `"foo/bar"`) go through the same git root search regardless of source
- Empty `base_path` returns git root (unchanged)
- Config-file dot-prefixed paths (`base_path: "."` in `atmos.yaml`) continue to resolve relative to the config directory

Verified by existing integration tests: `describe_component_from_nested_dir`, `terraform_plan_from_nested_dir`, `terraform_plan_with_current_directory`.

### Backward compatibility

- **Dot-prefixed paths from runtime sources** (`ATMOS_BASE_PATH="."`, `--base-path=./foo`): now resolve relative to CWD (shell convention). Previously resolved relative to config dir. This matches user expectations — in a shell, `.` means "here" (CWD)
- **Dot-prefixed paths from config file** (`base_path: "."` in `atmos.yaml`): continue to resolve relative to `atmos.yaml` location — no change
- **Bare paths** (`"stacks"`, `".terraform/modules/monorepo"`): go through git root search regardless of source, with `os.Stat` fallback to CWD — source-independent
- **Default/empty `base_path`**: continues to use git root discovery (the v1.202.0 behavior)
- **`ATMOS_GIT_ROOT_BASEPATH=false`**: continues to work as a full opt-out of git root discovery

## references

- closes #2183
- PRD: `docs/prd/base-path-resolution-semantics.md`
- Fix doc: `docs/fixes/2026-03-17-failed-to-find-import-base-path-resolution.md`
- Related: `terraform-provider-utils` v1.32.0+ with `ATMOS_BASE_PATH` env var

### CODE REVIEW

**Comment by osterman** [comment]
@aknysh please update and reconcile our PRD. I'm curious what our thinking was at the time. 

https://github.com/cloudposse/atmos/blob/main/docs/prd/base-path-resolution-semantics.md

**Comment by aknysh** [comment]
> @aknysh please update and reconcile our PRD. I'm curious what our thinking was at the time.
> 
> https://github.com/cloudposse/atmos/blob/main/docs/prd/base-path-resolution-semantics.md

The PRD has a gap that directly caused this bug. The PRD covers base_path values set in atmos.yaml, but it doesn't account for the different sources of base_path:

  1. atmos.yaml — the PRD's semantics make sense here. "foo" = search git root → config dir.
  2. ATMOS_BASE_PATH env var — FR4 (line 57) says it "overrides base_path in config file" but doesn't specify resolution semantics. The PRD treats it as if the override value follows the same resolution rules as config-file values, but that's
  wrong for simple relative paths.
  3. --base-path CLI flag / atmos_base_path provider parameter — not mentioned in the PRD at all.

  The core tension: The PRD says "foo" → search git root → config dir (line 28). This makes sense for config-file values (you'd write stacks in atmos.yaml meaning <project-root>/stacks). But when a user sets
  ATMOS_BASE_PATH=.terraform/modules/monorepo on a CI worker, they mean it relative to CWD, not git root. The PRD's design rationale (line 98) even quotes the v1.201.0 commit saying config-relative is correct for atmos.yaml, but that rationale
  doesn't apply to env vars or CLI flags.

  What needs reconciling:
  - FR4 needs to specify that ATMOS_BASE_PATH simple relative paths resolve relative to CWD, not git root — because env vars are set by the user in their shell context, not in a config file
  - A new FR should cover --base-path and atmos_base_path provider parameter with the same CWD-relative semantics
  - The detection logic (lines 129-141) needs a preamble: "if path was explicitly provided via env var or CLI flag, resolve simple relative paths via CWD"
  - The test cases section should include env-var and CLI-flag scenarios

  My opinion: Erik is right to flag this. The PRD formalized semantics for config-file values but didn't distinguish between sources. Our fix is consistent with the PRD's spirit (config-relative for config files, CWD-relative for user-provided
  overrides) but the PRD itself needs updating to codify this distinction.

File: pkg/config/config.go [hunk 1]
```diff
@@ -252,9 +242,30 @@ func resolveAbsolutePath(path string, cliConfigPath string) (string, error) {
...
-	// Resolve relative to config directory (cliConfigPath).
-	if isExplicitRelative && cliConfigPath != "" {
+	// For dot-prefixed paths: resolve based on source.
+	if isExplicitRelative {
+		return resolveDotPrefixPath(path, cliConfigPath, source)
+	}
+
+	// For empty path or simple relative paths (like "stacks", "components/terraform"):
+	// Try git root first.
+	return tryResolveWithGitRoot(path, isExplicitRelative, cliConfigPath)
```
[the remark this answers is not in the document]
Comment (aknysh) [reply pkg/config/config.go]: This is by design, not a bug. The PRD explicitly states bare paths are source-independent:

  Bare paths are source-independent. ATMOS_BASE_PATH=stacks and base_path: stacks in atmos.yaml go through the exact same git root search. The source only matters for dot-prefixed values.                                                         
                                                                                                                                                                                                                                                  
  And the design rationale:                                                                                                                                                                                                                         
                                                                       
  Making bare paths source-dependent would be confusing: ATMOS_BASE_PATH=stacks resolving to CWD/stacks while base_path: stacks resolves to git-root/stacks. Two different locations for the same value? That's the incongruence this PRD           
  eliminates.                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                  
  If both <git-root>/stacks and <cwd>/stacks exist, the git-root copy wins — that's intentional. The same value should resolve to the same place regardless of where it was specified.                                                              
                                                                                                                                                                                      
  If the user wants CWD-relative behavior from an env var, they use the dot-slash prefix: ATMOS_BASE_PATH=./stacks instead of ATMOS_BASE_PATH=stacks. That's the whole point of the "." ≠ "stacks" distinction in the PRD.                          
 
 The comment is technically accurate — bare paths from runtime sources do prefer git root when both locations exist — but this is intentional per the PRD (FR4: "Bare paths go through git root search regardless of         
  source").                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
  The key points:                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                    
  1. PRD FR4 explicitly defines bare paths as source-independent with git root priority                                                                                                                                                             
  2. The os.Stat fallback (step 2) handles the real-world case (.terraform/modules/monorepo doesn't exist at git root, so CWD fallback works)                                                                                               
  3. The escape hatch exists: if a user wants CWD-relative, they use ./stacks not stacks                                                             
  4. The design rationale (PRD lines 212-214): making bare paths source-dependent would mean ATMOS_BASE_PATH=stacks and base_path: stacks resolve to different locations for the same value — that's the confusion this design eliminates

File: docs/prd/base-path-resolution-semantics.md [hunk 2]
```diff
@@ -72,144 +168,160 @@ Atmos searches for `atmos.yaml` in the following order (highest to lowest priori
...
-base_path: ""           → /repo/config             (fallback to config dir)
-base_path: "."          → /repo/config             (config dir)
-base_path: ".."         → /repo                    (parent of config dir)
-base_path: "./foo"      → /repo/config/foo         (config-dir-relative)
-base_path: "../foo"     → /repo/foo                (parent of config dir)
-base_path: "foo"        → /repo/config/foo         (fallback to config-dir + foo)
-base_path: "foo/bar"    → /repo/config/foo/bar     (fallback to config-dir + foo/bar)
-base_path: "/abs/path"  → /abs/path                (absolute)
-base_path: !cwd         → /repo/src                (explicit CWD)
-```
```
Comment (osterman) [inline docs/prd/base-path-resolution-semantics.md:186]: Why did we delete this? This seems pretty clear to me.

File: docs/prd/base-path-resolution-semantics.md [hunk 3]
```diff
@@ -72,144 +168,160 @@ Atmos searches for `atmos.yaml` in the following order (highest to lowest priori
...
 
 ```
-if path == "" or path is unset:
-    return git_repo_root() or dirname(atmos.yaml)
-
-if path is absolute:
-    return path
-
-if path == "." or path starts with "./" or path == ".." or path starts with "../":
-    return dirname(atmos.yaml) / path  # Config-file-relative
```
Comment (osterman) [inline docs/prd/base-path-resolution-semantics.md:137]: This pseudocode was so much easier for me to read than the pseudocode below.

File: docs/prd/base-path-resolution-semantics.md (hunk 2 above)
Comment (aknysh) [reply docs/prd/base-path-resolution-semantics.md:186]: fixed

**Review by osterman — APPROVED** [review]
