### PR TITLE
fix: respect workdir path for generate: writes and hook-triggered terraform

### LINKED ISSUE #2307: Bug: store-outputs hook fires before JIT workdir is provisioned on terraform apply, causing backend file generation failure
### Describe the Bug

When a component uses JIT source provisioning (`source.uri` + `provision.workdir.enabled: true`) together with a `store-outputs` hook, running `atmos terraform apply` fails during the `before.terraform.apply` hook phase.

The hook attempts to read a Terraform output from the component (to fetch the previous value before apply). Doing so requires Atmos to generate the backend file (`backend.tf.json`) inside the JIT workdir. However, the workdir has not been provisioned yet at this point in the lifecycle — Atmos provisions the workdir for the terraform command itself, not for hooks that precede it. This means the path that `backend.tf.json` would be written to does not exist, and the operation fails.

`atmos terraform init` succeeds (workdir is provisioned as part of the init path before any output reads are attempted), but `atmos terraform apply` fails because the `before.terraform.apply` hook fires before workdir provisioning happens for that run.

Removing the `store-outputs` hook allows the apply to succeed, confirming the hook is the trigger.

### Expected Behavior

JIT workdir provisioning should occur before any hooks (including `before.terraform.apply`) that may need to access the Terraform backend for the component. Hooks should not be able to observe an unprovisioned workdir state.

### Actual Behavior

The `before.terraform.apply` hook fires, attempts to run `terraform output` against the JIT component, which requires generating `backend.tf.json` inside the (not-yet-provisioned) workdir. This results in:

```
ℹ Executing command: atmos terraform apply demo-vpc -auto-approve
 INFO  Running hooks event=before.terraform.apply
Fetching vpc_properties output from demo-vpc in dev

x Fetching vpc_properties output from demo-vpc in dev
# Error

Error: terraform output returned nil: failed to get terraform output for key
vpc_properties: failed to execute terraform output for component demo-vpc in
stack dev: failed to generate backend file: open
/tmp/gitrepo.fFs98Y/components/terraform/demo-vpc/backend.tf.json: no such file
or directory
```

### Steps to Reproduce

The script below is fully self-contained. It requires `atmos`, `tofu`, and `docker` on `PATH` and network access to GitHub. Redis is started via Docker to serve as the output store. Save it as `repro.sh` and run it.

The script runs **two scenarios** back-to-back: a success case (no hooks) to confirm JIT + workdir works on its own, then the failure case (hook on `before-terraform-apply`).

**Run:**
```bash
cat << 'SCRIPT' > repro.sh
#!/usr/bin/env bash
# ============================================================
# ATMOS REPRO: JIT workdir not provisioned before hooks fire
#
# Stack name:  demo       (from vars.name + name_template)
# Component:   null-label (key under components.terraform)
# Commands:    atmos terraform <cmd> null-label -s demo
#
# Requires: atmos, tofu, docker
# ============================================================

set -euo pipefail

# --- 0) Create isolated workspace ---
WORKDIR="$(mktemp -d -t atmos-repro-XXXXXX)"
echo "Working in: ${WORKDIR}"
cd "${WORKDIR}"

# --- 1) Start a local Redis instance for the store ---
echo "== starting redis =="
docker stop atmos-repro-redis 2>/dev/null || true
docker run -d --rm --name atmos-repro-redis -p 6379:6379 redis:7-alpine
trap 'docker stop atmos-repro-redis 2>/dev/null || true' EXIT
sleep 1

# --- 2) Write atmos.yaml (shared across both scenarios) ---
cat <<'EOF' > atmos.yaml
base_path: "."

stores:
  local/redis:
    type: redis
    options:
      url: "redis://localhost:6379"

components:
  terraform:
    base_path: "components/terraform"
    command: "tofu"
    workspaces_enabled: true
    apply_auto_approve: false
    deploy_run_init: true
    init_run_reconfigure: true
    auto_generate_backend_file: true

stacks:
  name_template: "{{ .vars.name }}"
  base_path: "stacks"
  included_paths:
    - "**/*"
EOF

mkdir -p stacks

cleanup() {
  echo "-- cleanup --"
  atmos terraform workdir clean --all 2>/dev/null || true
  echo "-- cleanup done --"
}

# ============================================================
# SCENARIO 1 (SUCCESS): JIT + workdir WITHOUT hooks
# Confirms the component itself works fine — the bug is
# introduced by the before-terraform-apply hook.
# ============================================================
echo
echo "================================================="
echo "SCENARIO 1: apply WITHOUT hooks (expect success)"
echo "================================================="
cleanup

cat <<'EOF' > stacks/demo.yaml
vars:
  name: demo

terraform:
  backend_type: local

components:
  terraform:
    null-label:
      vars:
        namespace: "eg"
        stage: "test"
        name: "demo"
        enabled: true
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      # NO hooks — baseline to confirm JIT + workdir works
EOF

echo "== init =="
atmos terraform init null-label -s demo

echo "== apply =="
atmos terraform apply null-label -s demo -- -auto-approve
echo "SCENARIO 1: PASSED (success as expected)"

# ============================================================
# SCENARIO 2 (FAILURE): JIT + workdir WITH before-apply hook
# The before.terraform.apply hook fires before the workdir is
# provisioned, so backend.tf.json does not exist yet.
# ============================================================
echo
echo "================================================="
echo "SCENARIO 2: apply WITH before-apply hook (expect failure)"
echo "================================================="
cleanup

cat <<'EOF' > stacks/demo.yaml
vars:
  name: demo

terraform:
  backend_type: local

components:
  terraform:
    null-label:
      vars:
        namespace: "eg"
        stage: "test"
        name: "demo"
        enabled: true
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      hooks:
        store-outputs:
          events:
            - before-terraform-apply
          command: store
          name: local/redis
          outputs:
            label_id: .id
EOF

echo "== init =="
atmos terraform init null-label -s demo

echo "== apply (expected to FAIL) =="
set +e
atmos terraform apply null-label -s demo -- -auto-approve
EXIT_CODE=$?
set -e

if [[ $EXIT_CODE -ne 0 ]]; then
  echo "SCENARIO 2: FAILED (failure expected — bug confirmed)"
else
  echo "SCENARIO 2: UNEXPECTEDLY SUCCEEDED — bug may be fixed"
fi

echo
echo "Done. Workspace preserved at: ${WORKDIR}"
SCRIPT
bash repro.sh 2>&1 | tee repro.log
```

> **Note:** `docker` is required only for the local Redis instance. If you already have Redis running on `localhost:6379`, remove the `docker run` block and `trap`. The store type is otherwise not relevant to the bug — the failure occurs when the hook tries to call `terraform output`, before the store write is even attempted.

### Screenshots

_No response_

### Environment

Atmos 1.214.0 on linux/arm64

### Additional Context

- `atmos terraform init null-label -s demo` succeeds — workdir is provisioned before init runs.
- `atmos terraform apply null-label -s demo` fails — the `before.terraform.apply` hook fires before the workdir is provisioned for the apply run.
- Removing the `hooks` block from the component config allows apply to succeed.
- The issue is not store-specific; the error occurs before the store is ever contacted. Any hook event on `before.terraform.apply` that causes Atmos to call `terraform output` (and thus generate `backend.tf.json`) will trigger this failure when the component uses JIT workdir provisioning.

**Suspected root cause:** The JIT workdir provisioning lifecycle is tied to the terraform command invocation, not to the surrounding hook lifecycle. Hooks that fire on `before.terraform.apply` should see a fully provisioned workdir.

### LINKED ISSUE #2308: Bug: When `provision.workdir.enabled: true`, atmos incorrectly uses base component directory for generate: writes and hook-triggered terraform
### Describe the Bug

When `provision.workdir.enabled: true` is set on a component, atmos provisions the component source into a JIT workdir (`.workdir/terraform/<stack>-<component>/`) and all terraform operations should run from there. The base component directory (`components.terraform.base_path/<component>/` — `components/terraform/<component>/` in this repro) has no primary source and should not be used at all.

Atmos does not respect this. It continues to use the base component directory for certain operations even when JIT workdir provisioning is active:

- **`generate:` writes to the base component directory.** Generated files (e.g. `locals_override.tf`) are written to both the base component directory and the JIT workdir. In the base component directory there is no primary source, so override files have nothing to override against.
- **Hooks target the base component directory, not the workdir.** When a `before-terraform-apply` hook fetches component outputs, atmos runs `terraform output` against the base component directory rather than the JIT workdir. This triggers `terraform init` there, which fails because the orphaned override file has no corresponding base definition: `"Missing base local value definition to override"`.

### Expected Behavior

When `provision.workdir.enabled: true` is configured, atmos should treat the JIT workdir as the exclusive working directory for that component. The base component directory should not be read from, written to, or targeted by any atmos operation — including `generate:` file writes, hook-triggered terraform commands, and backend file generation.

### Actual Behavior

During `atmos terraform init`, `generate:` files are written to **both** paths:

```
Created: components/terraform/null-label/locals_override.tf    ← should NOT happen
✓ Generated components/terraform/null-label (1 created)
✓ Auto-provisioned source to .workdir/terraform/demo-null-label
Created: .workdir/terraform/demo-null-label/locals_override.tf ← correct
✓ Generated .workdir/terraform/demo-null-label (1 created)
```

After init, the base component directory has the orphaned override file and no primary source:

```
components/terraform/null-label/
└── locals_override.tf          ← override with nothing to override

.workdir/terraform/demo-null-label/
├── main.tf                     ← primary source (defines local.name)
├── locals_override.tf          ← override correctly colocated with source
├── backend.tf.json
└── ...
```

When a `before-terraform-apply` hook fires and fetches component outputs, atmos runs `terraform output` targeting the base component directory (`components/terraform/null-label/`) instead of the JIT workdir. This generates `backend.tf.json` there and runs `tofu init`, which fails:

```
Error: Missing base local value definition to override
on locals_override.tf line 3, in locals:
  3:   name = "THISISANOVERRIDE"
There is no local value named "name". An override file can only override a
local value that was already defined in a primary configuration file.
```

### Steps to Reproduce

The script below is fully self-contained. It requires `atmos`, `tofu`, and `docker` on `PATH` and network access to GitHub. Redis is started via Docker to serve as the output store for the hook.

The script runs two scenarios: init + apply without a hook (succeeds — shows the double-write behavior); then init + apply with a `before-terraform-apply` hook (fails — hook triggers `terraform init` against the base component directory which has the orphaned override).

**Run:**

```bash
cat << 'SCRIPT' > repro.sh
#!/usr/bin/env bash
# ============================================================
# ATMOS REPRO: generate: writes orphaned override to base
#              component directory; hook-triggered terraform fails
#
# Stack name:  demo       (from vars.name + name_template)
# Component:   null-label (key under components.terraform)
#
# Requires: atmos, tofu, docker
# ============================================================

set -euo pipefail

WORKDIR="$(mktemp -d -t atmos-repro-XXXXXX)"
echo "Working in: ${WORKDIR}"
cd "${WORKDIR}"

echo "== starting redis =="
docker stop atmos-repro-redis 2>/dev/null || true
docker run -d --rm --name atmos-repro-redis -p 6379:6379 redis:7-alpine
trap 'docker stop atmos-repro-redis 2>/dev/null || true' EXIT
sleep 1

cat <<'EOF' > atmos.yaml
base_path: "."

stores:
  local/redis:
    type: redis
    options:
      url: "redis://localhost:6379"

components:
  terraform:
    base_path: "components/terraform"
    command: "tofu"
    workspaces_enabled: true
    apply_auto_approve: false
    deploy_run_init: true
    init_run_reconfigure: true
    auto_generate_backend_file: true
    auto_generate_files: true

stacks:
  name_template: "{{ .vars.name }}"
  base_path: "stacks"
  included_paths:
    - "**/*"
EOF

mkdir -p stacks

cleanup() {
  echo "-- cleanup --"
  atmos terraform workdir clean --all 2>/dev/null || true
  echo "-- cleanup done --"
}

show_dirs() {
  echo
  echo "-- base component directory (should be EMPTY for JIT components) --"
  echo "components/terraform/null-label"
  ls -la components/terraform/null-label/ 2>/dev/null || echo "(does not exist)"
  echo "-- JIT workdir (source + generated files should be here) --"
  echo ".workdir/terraform/demo-null-label"
  ls -la .workdir/terraform/demo-null-label/ 2>/dev/null || echo "(does not exist)"
}

# ============================================================
# SCENARIO 1: JIT + generate, no hook.
# Shows generate: incorrectly writing to the base component
# directory in addition to the JIT workdir.
# Direct atmos commands succeed because they use the workdir.
# ============================================================
echo
echo "================================================="
echo "SCENARIO 1: init + apply WITHOUT hook (expect success)"
echo "  - shows generate: double-write to both paths"
echo "================================================="
cleanup

cat <<'EOF' > stacks/demo.yaml
vars:
  name: demo

terraform:
  backend_type: local

components:
  terraform:
    null-label:
      vars:
        namespace: "eg"
        stage: "test"
        name: "demo"
        enabled: true
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      generate:
        locals_override.tf: |
          # override file generated by atmos
          locals {
            name = "THISISANOVERRIDE"
          }
EOF

echo "== init =="
atmos terraform init null-label -s demo

echo
echo "==> After init:"
show_dirs

echo
echo "== apply =="
atmos terraform apply null-label -s demo -- -auto-approve

echo
echo "==> After apply:"
show_dirs

echo
echo "SCENARIO 1: PASSED (apply succeeded)"

# ============================================================
# SCENARIO 2: JIT + generate + before-apply hook.
# The hook runs terraform output against the base component
# directory (not the workdir), where the orphaned override
# causes terraform init to fail.
# ============================================================
echo
echo "================================================="
echo "SCENARIO 2: init + apply WITH before-apply hook (expect failure)"
echo "  - hook runs terraform output against base component directory"
echo "  - orphaned override in base component directory causes init to fail"
echo "================================================="
cleanup

cat <<'EOF' > stacks/demo.yaml
vars:
  name: demo

terraform:
  backend_type: local

components:
  terraform:
    null-label:
      vars:
        namespace: "eg"
        stage: "test"
        name: "demo"
        enabled: true
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      generate:
        locals_override.tf: |
          # override file generated by atmos
          locals {
            name = "THISISANOVERRIDE"
          }
      hooks:
        store-outputs:
          events:
            - before-terraform-apply
          command: store
          name: local/redis
          outputs:
            label_id: .id
EOF

echo "== init =="
atmos terraform init null-label -s demo

echo
echo "==> After init:"
show_dirs

echo
echo "== apply (expected to FAIL) =="
set +e
atmos terraform apply null-label -s demo -- -auto-approve
EXIT_CODE=$?
set -e

echo
echo "==> After failed apply — hook wrote to base component directory:"
show_dirs

if [[ $EXIT_CODE -ne 0 ]]; then
  echo
  echo "SCENARIO 2: FAILED (failure expected — bug confirmed)"
else
  echo
  echo "SCENARIO 2: UNEXPECTEDLY SUCCEEDED — bug may be fixed"
fi

echo
echo "Done. Workspace preserved at: ${WORKDIR}"
SCRIPT
bash repro.sh 2>&1 | tee repro.log
```

### Repro Output

**Scenario 1** (no hook — shows double-write during init, apply succeeds):

```
== init ==
Created: components/terraform/null-label/locals_override.tf    ← BUG: should not be written here
✓ Created components/terraform/null-label/locals_override.tf
✓ Generated components/terraform/null-label (1 created)
✓ Auto-provisioned source to .workdir/terraform/demo-null-label
Created: .workdir/terraform/demo-null-label/locals_override.tf ← correct
✓ Created .workdir/terraform/demo-null-label/locals_override.tf
✓ Generated .workdir/terraform/demo-null-label (1 created)

==> After init:
-- base component directory (should be EMPTY for JIT components) --
components/terraform/null-label
locals_override.tf                          ← BUG: should not exist here

-- JIT workdir (source + generated files should be here) --
.workdir/terraform/demo-null-label
backend.tf.json  descriptors.tf  LICENSE  locals_override.tf
main.tf  outputs.tf  variables.tf  versions.tf  ...

...apply succeeds — direct atmos commands correctly target the workdir...

SCENARIO 1: PASSED (apply succeeded)
```

**Scenario 2** (with `before-terraform-apply` hook — hook targets base component directory, init fails):

```
== init ==
✓ Auto-provisioned source to .workdir/terraform/demo-null-label
Created: .workdir/terraform/demo-null-label/locals_override.tf
✓ Generated .workdir/terraform/demo-null-label (1 created)

==> After init:
-- base component directory (should be EMPTY for JIT components) --
components/terraform/null-label
locals_override.tf                          ← BUG: should not exist here

-- JIT workdir (source + generated files should be here) --
.workdir/terraform/demo-null-label
backend.tf.json  descriptors.tf  LICENSE  locals_override.tf
main.tf  outputs.tf  variables.tf  versions.tf  ...

== apply (expected to FAIL) ==
 INFO  Running hooks event=before.terraform.apply
Fetching id output from null-label in demo

x Fetching id output from null-label in demo
# Error

Error: terraform output returned nil: failed to get terraform output for key
id: failed to execute terraform output for component null-label in stack demo:
terraform init failed: exit status 1 OpenTofu encountered problems during
initialization, including problems with the configuration, described below.
The OpenTofu configuration must be valid before initialization so that
OpenTofu can determine which modules and providers need to be installed.
Error: Missing base local value definition to override
on locals_override.tf line 3, in locals:
  3:   name = "THISISANOVERRIDE"
There is no local value named "name". An override file can only override a
local value that was already defined in a primary configuration file.

==> After failed apply — hook wrote to base component directory:
-- base component directory (should be EMPTY for JIT components) --
components/terraform/null-label
total 16
drwxr-xr-x  5 user  staff  160 .
drwxr-xr-x  3 user  staff   96 ..
drwxr-xr-x  3 user  staff   96 .terraform          ← hook ran tofu init here
-rw-r--r--  1 user  staff   66 backend.tf.json     ← hook generated backend here
-rw-r--r--  1 user  staff   74 locals_override.tf  ← orphaned override with no source

-- JIT workdir (source + generated files should be here) --
.workdir/terraform/demo-null-label
total 288
drwxr-xr-x  22 user  staff    704 .
drwxr-xr-x   3 user  staff     96 ..
drwxr-xr-x   4 user  staff    128 .atmos
drwxr-xr-x   7 user  staff    224 .github
-rw-r--r--   1 user  staff    192 .gitignore
drwxr-xr-x   3 user  staff     96 .terraform
-rw-r--r--   1 user  staff  11351 LICENSE
-rw-r--r--   1 user  staff    389 Makefile
-rw-r--r--   1 user  staff  49758 README.md
-rw-r--r--   1 user  staff  23487 README.yaml
-rw-------   1 user  staff     66 backend.tf.json
-rw-r--r--   1 user  staff     80 demo-null-label.terraform.tfvars.json
-rw-r--r--   1 user  staff   1138 descriptors.tf
drwxr-xr-x   4 user  staff    128 docs
drwxr-xr-x   4 user  staff    128 examples
drwxr-xr-x   3 user  staff     96 exports
-rw-r--r--   1 user  staff     74 locals_override.tf
-rw-r--r--   1 user  staff  10362 main.tf
-rw-r--r--   1 user  staff   2790 outputs.tf
drwxr-xr-x   6 user  staff    192 test
-rw-r--r--   1 user  staff   8231 variables.tf
-rw-r--r--   1 user  staff     47 versions.tf

SCENARIO 2: FAILED (failure expected — bug confirmed)
```

### Screenshots

_No response_

### Environment

Atmos 1.214.0 on linux/arm64 / darwin/arm64

### Additional Context

Without a `generate:` block the base component directory is never written to, so hooks fail differently — with a missing directory error rather than a broken override (see companion bug: JIT workdir not provisioned before hooks fire). The `generate:` block is what populates the base component directory with a broken file, causing `terraform init` to fail whenever the hook targets it.

### PR DESCRIPTION
**Pull request by zack-is-cool**
## Summary

Fixes a cluster of bugs in `provision.workdir.enabled: true` mode covering file generation, hook dispatch, store hook correctness, and repeated-apply terraform init prompts.

---

**Bug 1 – `generate:` writes to base component directory instead of workdir**

`resolveAndProvisionComponentPath` called `autoGenerateComponentFiles` before `provisionComponentSource`. Generated files (e.g. `locals_override.tf`) were written to `components/terraform/<component>/` instead of the JIT workdir.

Fix: swap call order — provision source first, then generate into the returned (workdir) path.

---

**Bug 2 – hooks and output executor used base component directory**

`extractComponentPath` always returned the base component directory because `_workdir_path` is a runtime key absent from freshly-described sections. Hooks calling `terraform output` would fail with _"no such file or directory"_ when trying to write `backend.tf.json` to a path that doesn't exist.

Fix: check `provision.workdir.enabled` in sections and rebuild the deterministic workdir path via `workdir.BuildPath`.

---

**Bug 3 – hooks fired on every event regardless of `events:` list**

`RunAll` had no event matching — all hooks ran regardless of their `events:` list. YAML uses hyphens (`after-terraform-apply`) but Go `HookEvent` constants use dots (`after.terraform.apply`).

Fix: added `MatchesEvent()` with hyphen→dot normalisation. Hooks with no `events:` field match all events to preserve backward compatibility with configs written before event filtering existed.

---

**Bug 4 – store hook used wrong output getter and wrong error sentinels**

The store hook always used `GetOutput` (which runs `terraform init`) regardless of when it fires. Running init after apply with a closed stdin triggers state-migration prompts. Additionally, errors used `ErrNilTerraformOutput` for both retrieval failures and missing keys, and included no context about which hook or event caused the failure.

Fix: `RunE` now selects the getter based on the event — `after-` events use `GetOutputSkipInit` (workdir already initialised); `before-` events use `GetOutput` (init may not have run yet). `IsPostExecution()` helper on `HookEvent` encodes the contract. Error messages now include hook name, event, output key, component, and stack. Correct sentinels: `ErrTerraformOutputFailed` for retrieval errors, `ErrTerraformOutputNotFound` for missing keys.

---

**Bug 5 – "Do you want to migrate all workspaces?" prompt on every apply**

This was caused by three interacting problems:

1. **`-reconfigure` added whenever `WorkdirPathKey` was set** — `WorkdirPathKey` is set for both a preserved workdir (TTL not expired) and a wiped/re-provisioned workdir (TTL=0s or expired). Checking it unconditionally added `-reconfigure` even when `.terraform/` was intact.

2. **`init_run_reconfigure: true` overriding the preserved-workdir guard** — even after scoping `-reconfigure` to `WorkdirReprovisionedKey`, the global `InitRunReconfigure` flag bypassed the check and always added `-reconfigure`.

3. **`cleanTerraformWorkspace` deleting `.terraform/environment` for workdir components** — this function was designed for backend-switching on non-workdir components. For workdir components it deleted the active workspace record before every init, causing OpenTofu to see orphaned `terraform.tfstate.d/<workspace>/` directories with no active workspace and prompt for migration.

When combined: `-reconfigure` tells OpenTofu to ignore the saved backend and treat init as fresh. A fresh-init with existing workspace state dirs triggers the migration prompt even when the backend is unchanged.

Fix (three parts):
- Introduce `WorkdirReprovisionedKey` (`_workdir_reprovisioned`), set only by `vendorToTarget` (source wiped) or `SyncDir` with file changes (workdir synced). This is the correct signal that `.terraform/` was actually cleared.
- For workdir components with a **preserved** workdir, ignore `InitRunReconfigure` — the backend is always generated deterministically from the same stack config and never changes between runs. `-reconfigure` is only added when `WorkdirReprovisionedKey` is set or the subcommand is `workspace`.
- Skip `cleanTerraformWorkspace` for workdir-enabled components — the backend is consistent, so there is no reason to clear the workspace record.

---

## Tested end-to-end

Full producer → store → consumer pipeline:

1. `null-label` applies with JIT workdir + `generate:` override
2. `after-terraform-apply` hook reads `.id` output and writes it to Redis (no init re-run, no migration prompt)
3. `consumer` reads the value via `!store local/redis null-label label_id`, injects it into its own `generate:` template, applies successfully
4. Repeated applies do not prompt for workspace migration, with or without `init_run_reconfigure: true` and with or without `ttl: "0s"`

Reproduction
This worked successfully for the deployment that I was initially having this issue with. Local reproduction below.

```
cat << 'SCRIPT' > repro.sh
#!/usr/bin/env bash
# ============================================================
# ATMOS REPRO: generate: writes orphaned override to base
#              component directory; hook-triggered terraform fails;
#              consumer reads store value into JIT workdir generate:
#
# Stack name:  demo       (from vars.name + name_template)
# Components:  null-label (producer), consumer (reads from store)
#
# Requires: atmos, tofu, docker
# ============================================================

set -euo pipefail

WORKDIR="$(mktemp -d -t atmos-repro-XXXXXX)"
echo "Working in: ${WORKDIR}"
cd "${WORKDIR}"

echo "== starting redis =="
docker stop atmos-repro-redis 2>/dev/null || true
docker run -d --rm --name atmos-repro-redis -p 6379:6379 redis:7-alpine
trap 'docker stop atmos-repro-redis 2>/dev/null || true' EXIT
sleep 1

cat <<'EOF' > atmos.yaml
base_path: "."

stores:
  local/redis:
    type: redis
    options:
      url: "redis://localhost:6379"

components:
  terraform:
    base_path: "components/terraform"
    command: "tofu"
    workspaces_enabled: true
    apply_auto_approve: false
    deploy_run_init: true
    init_run_reconfigure: true
    auto_generate_backend_file: true
    auto_generate_files: true

stacks:
  name_template: "{{ .vars.name }}"
  base_path: "stacks"
  included_paths:
    - "**/*"
EOF

mkdir -p stacks

cleanup() {
  echo "-- cleanup --"
  atmos terraform workdir clean --all 2>/dev/null || true
  echo "-- cleanup done --"
}

show_dirs() {
  local label="${1:-}"
  echo
  if [[ -n "$label" ]]; then
    echo "-- directories: $label --"
  fi
  echo "components/terraform/null-label"
  ls -la components/terraform/null-label/ 2>/dev/null || echo "(does not exist)"
  echo ".workdir/terraform/demo-null-label"
  ls -la .workdir/terraform/demo-null-label/ 2>/dev/null || echo "(does not exist)"
  echo ".workdir/terraform/demo-consumer"
  ls -la .workdir/terraform/demo-consumer/ 2>/dev/null || echo "(does not exist)"
}

# ============================================================
# SCENARIO 1: JIT + generate, no hook.
# Verifies generate: writes to the workdir only (not the base
# component directory), and that apply succeeds.
# ============================================================
echo
echo "================================================="
echo "SCENARIO 1: init + apply WITHOUT hook (expect success)"
echo "  - generate: must write only to workdir, not base component dir"
echo "================================================="
cleanup

cat <<'EOF' > stacks/demo.yaml
vars:
  name: demo

terraform:
  backend_type: local

components:
  terraform:
    null-label:
      vars:
        namespace: "eg"
        stage: "test"
        name: "demo"
        enabled: true
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      generate:
        locals_override.tf: |
          # override file generated by atmos
          locals {
            name = "THISISANOVERRIDE"
          }
EOF

echo "== init =="
atmos terraform init null-label -s demo

show_dirs "after init"

echo "== apply =="
atmos terraform apply null-label -s demo -- -auto-approve

show_dirs "after apply"

echo
echo "SCENARIO 1: PASSED"

# ============================================================
# SCENARIO 2: JIT + generate + after-apply hook writes to Redis.
# The hook fires after apply, reads terraform output, and stores
# it in Redis. Tests that the hook does not re-run init (which
# would prompt for workspace migration with a closed stdin).
# ============================================================
echo
echo "================================================="
echo "SCENARIO 2: init + apply WITH after-apply store hook (expect success)"
echo "  - hook reads .id output and stores it in Redis"
echo "  - hook must NOT re-run terraform init"
echo "================================================="
cleanup

cat <<'EOF' > stacks/demo.yaml
vars:
  name: demo

terraform:
  backend_type: local

components:
  terraform:
    null-label:
      vars:
        namespace: "eg"
        stage: "test"
        name: "demo"
        enabled: true
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      generate:
        locals_override.tf: |
          # override file generated by atmos
          locals {
            name = "THISISANOVERRIDE"
          }
      hooks:
        store-outputs:
          events:
            - after-terraform-apply
          command: store
          name: local/redis
          outputs:
            label_id: .id
EOF

echo "== init =="
atmos terraform init null-label -s demo

echo "== apply =="
atmos terraform apply null-label -s demo -- -auto-approve

show_dirs "after apply"

echo
echo "== verifying Redis contains label_id =="
STORED=$(docker exec atmos-repro-redis redis-cli KEYS "*label_id*")
if [[ -z "$STORED" ]]; then
  echo "SCENARIO 2: FAILED — no label_id key found in Redis"
  exit 1
fi
echo "Redis keys: $STORED"
echo
echo "SCENARIO 2: PASSED"

# ============================================================
# SCENARIO 3: Consumer reads label_id from Redis via !store,
# injects it into a generate: template inside its own JIT workdir.
# Tests the full producer → store → consumer pipeline.
# ============================================================
echo
echo "================================================="
echo "SCENARIO 3: consumer reads store value into JIT workdir generate:"
echo "  - consumer.vars.label_id: !store local/redis null-label label_id"
echo "  - generate: uses {{ .vars.label_id }} in a locals override"
echo "  - both components use JIT workdir with ttl: 0s"
echo "================================================="

cat <<'EOF' > stacks/demo.yaml
vars:
  name: demo

terraform:
  backend_type: local

components:
  terraform:
    null-label:
      vars:
        namespace: "eg"
        stage: "test"
        name: "demo"
        enabled: true
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      generate:
        locals_override.tf: |
          # override file generated by atmos
          locals {
            name = "THISISANOVERRIDE"
          }
      hooks:
        store-outputs:
          events:
            - after-terraform-apply
          command: store
          name: local/redis
          outputs:
            label_id: .id

    consumer:
      vars:
        namespace: "eg"
        stage: "test"
        enabled: true
        label_id: !store local/redis null-label label_id
      source:
        uri: "git::https://github.com/cloudposse/terraform-null-label.git"
        version: "0.25.0"
        ttl: "0s"
      provision:
        workdir:
          enabled: true
      generate:
        name_override.tf: |
          # override file generated by atmos — value comes from Redis via !store
          locals {
            name = "{{ .vars.label_id }}-derpderpderp"
          }
EOF

echo "== apply consumer =="
atmos terraform apply consumer -s demo -- -auto-approve

show_dirs "after consumer apply"

echo
echo "== verifying consumer output contains the store value =="
CONSUMER_ID=$(atmos terraform output consumer -s demo 2>/dev/null |  grep "id =" | head -1)
echo "Consumer id output line: $CONSUMER_ID"

if echo "$CONSUMER_ID" | grep -q "derpderpderp"; then
  echo
  echo "SCENARIO 3: PASSED — consumer label contains store-derived value"
else
  echo
  echo "SCENARIO 3: FAILED — consumer output does not contain expected suffix"
  echo "  Expected 'derpderpderp' in id output"
  exit 1
fi

echo
echo "================================================="
echo "ALL SCENARIOS PASSED"
echo "Working directory preserved at: ${WORKDIR}"
echo "================================================="
SCRIPT
bash repro.sh 2>&1 | tee repro.log
```

## Test plan

- [x] `TestHook_MatchesEvent` — hyphen/dot formats, no match, nil/empty events (backward compat), multiple events
- [x] `TestRunAll_EventFiltering` — store called/skipped based on event matching
- [x] `TestExecutor_GetOutputWithOptions_SkipInit` — `terraform init` NOT called when `SkipInit: true`
- [x] `TestBuildInitArgs_ReconfigureWhenWorkdirReprovisioned` — `-reconfigure` added when workdir wiped
- [x] `TestBuildInitArgs_NoReconfigureWhenWorkdirPreserved` — `-reconfigure` NOT added for preserved workdir
- [x] `TestBuildInitArgs_NoReconfigureWhenWorkdirPreserved_InitRunReconfigureIgnored` — global `InitRunReconfigure: true` does not override the preserved-workdir guard
- [x] `TestBuildInitArgs_ReconfigureForNonWorkdir_InitRunReconfigure` — `InitRunReconfigure` still works for non-workdir components
- [x] `TestPrepareInitExecution_SkipsCleanWorkspaceForWorkdir` — `.terraform/environment` preserved for workdir components
- [x] `TestPrepareInitExecution_CleansWorkspaceForNonWorkdir` — `.terraform/environment` still cleaned for non-workdir components
- [x] `TestIsWorkdirEnabled` / `TestExtractComponentPath/workdir_enabled_*` — workdir path resolution
- [x] Full `pkg/hooks`, `pkg/terraform/output`, `internal/exec` test suites pass

Closes #2308
Closes #2307

## Summary by CodeRabbit

* **New Features**
  * Workdir-aware provisioning that targets JIT workdirs and signals reprovisioning
  * Hook event normalization, post-execution detection, and event-matching/filtering
  * New output APIs including skip-init retrieval and advanced output options

* **Improvements**
  * Smarter terraform init (-reconfigure) behavior for workdir flows
  * Preserve workspace files for workdir components to avoid unintended deletions
  * More robust output caching and clearer CLI success/error messaging

* **Tests**
  * Expanded coverage for workdirs, init args, hooks, output paths, and store commands

### CODE REVIEW

File: pkg/hooks/hook.go [hunk 1]
```diff
@@ -16,3 +18,21 @@ type Hook struct {
...
 	// component provider bindings. See pkg/ci/ for the modern implementation.
 }
+
+// MatchesEvent reports whether this hook should run for the given event.
+// It normalises the yaml event format (hyphens, e.g. "after-terraform-apply")
+// to the canonical Go format (dots, e.g. "after.terraform.apply") before
+// comparing, so both styles are accepted in stack configuration.
+//
+// If the hook has no events configured, it matches all events to preserve
+func (h Hook) MatchesEvent(event HookEvent) bool {
```
[the remark this answers is not in the document]
Comment (zack-is-cool) [reply pkg/hooks/hook.go:29]: Fixed

File: pkg/terraform/output/executor.go [hunk 2]
```diff
@@ -299,6 +299,103 @@ func (e *Executor) GetOutput(
...
+
+	// Execute terraform output with caller-supplied options.
+	ctx, cancel := context.WithTimeout(context.Background(), time.Minute*5)
+	defer cancel()
+
+	outputs, err := e.execute(ctx, atmosConfig, component, stack, sections, authContext, opts)
+	if err != nil {
+		u.PrintfMessageToTUI(terminal.EscResetLine+"%s %s\n", theme.Styles.XMark, message)
+		return nil, false, fmt.Errorf("failed to execute terraform output for component %s in stack %s: %w", component, stack, err)
+	}
```
[the remark this answers is not in the document]
Comment (zack-is-cool) [reply pkg/terraform/output/executor.go:420]: it has been done rabbit

**Comment by osterman** [comment]
> Bug 3 – hooks fired on every event regardless of events: list


@coderabbitai I'm concerned about this conclusion. I just want to be clear that hooks are used, not just from the YAML in configs, but as the core plumbing within Atmos that provisioning ties into. So the events list in YAML isn't the exhaustive list.

**Comment by zack-is-cool** [comment]
Looking at the acceptance tests now 👀

**Comment by zack-is-cool** [comment]
claude blamed @coderabbitai for breaking the test 😂

**Comment by zack-is-cool** [comment]
Ok, I think this is ready to be ran again.
I think some of the fixes that were introduced to the hook events broke the tests, because they filter properly now

cc @osterman

**Comment by zack-is-cool** [comment]
apparently with the fixes, these are both valid

```
      hooks:
        store-outputs:
          events:
            - after-terraform-apply
```

```
      hooks:
        store-outputs:
          events:
            - after-terraform-deploy
```

And each of them will trigger based on differences how you call atmos

Will trigger: after-terraform-deploy `atmos terraform deploy null-label -s demo`

Will trigger: after-terraform-apply `atmos terraform apply  null-label -s demo -auto-approve`

Do we like this? kind of feel like the event should catch either or? @osterman 

I'm going to go ahead and make them the same under-the-hood because this will be a really annoying bug for someone in the future. I can't imagine a scenario where someone would want to differentiate between a deploy and an apply when it comes to ingesting/consuming parameters from their store.

**Comment by zack-is-cool** [comment]
@coderabbitai spot check pls. Will I pass integration testing? How about my recent changes to hook events for making deploy=apply under the hood?

File: pkg/terraform/output/executor.go [hunk 3]
```diff
@@ -294,7 +294,110 @@ func (e *Executor) GetOutput(
...
+	defer perf.Track(atmosConfig, "output.Executor.GetOutputWithOptions")()
+
+	// Validate authManager type if provided.
+	if authManager != nil {
+		if _, ok := authManager.(auth.AuthManager); !ok {
+			return nil, false, fmt.Errorf("%w: expected auth.AuthManager", errUtils.ErrInvalidAuthManagerType)
+		}
+	}
+
+	stackSlug := fmt.Sprintf("%s-%s", stack, component)
```
Comment (osterman) [inline pkg/terraform/output/executor.go]: This seems curve fitted and assumes stack name convention.

File: pkg/terraform/output/executor.go [hunk 4]
```diff
@@ -294,7 +294,110 @@ func (e *Executor) GetOutput(
...
+			WithExplanationf("failed to execute terraform output for component %s in stack %s", component, stack).
+			Err()
+	}
+
+	// Cache the result.
+	terraformOutputsCache.Store(stackSlug, outputs)
+
+	value, exists, resultErr := getOutputVariable(atmosConfig, component, stack, outputs, output)
+	if resultErr != nil {
+		u.PrintfMessageToTUI(terminal.EscResetLine+"%s %s\n", theme.Styles.XMark, message)
```
Comment (osterman) [inline pkg/terraform/output/executor.go]: This function is deprecated. We should use `ui.*` methods everywhere.

File: pkg/terraform/output/executor.go [hunk 5]
```diff
@@ -294,7 +294,110 @@ func (e *Executor) GetOutput(
...
+		return nil, false, resultErr
+	}
+
+	u.PrintfMessageToTUI(terminal.EscResetLine+"%s %s\n", theme.Styles.Checkmark, message)
```
Comment (osterman) [inline pkg/terraform/output/executor.go]: This should be a `ui.` method.

File: pkg/terraform/output/executor.go [hunk 6]
```diff
@@ -294,7 +294,110 @@ func (e *Executor) GetOutput(
...
+	sections, err := e.componentDescriber.DescribeComponent(&DescribeComponentParams{
+		AtmosConfig:          atmosConfig,
+		Component:            component,
+		Stack:                stack,
+		ProcessTemplates:     true,
+		ProcessYamlFunctions: processYamlFunctions,
+		AuthManager:          authManager,
+	})
+	if err != nil {
+		u.PrintfMessageToTUI(terminal.EscResetLine+"%s %s\n", theme.Styles.XMark, message)
```
Comment (osterman) [inline pkg/terraform/output/executor.go]: Replace with `ui` method.

File: pkg/terraform/output/executor.go [hunk 7]
```diff
@@ -294,7 +294,110 @@ func (e *Executor) GetOutput(
...
+	// Check for static remote state backend.
+	if e.staticRemoteStateGetter != nil {
+		if staticOutputs := e.staticRemoteStateGetter.GetStaticRemoteStateOutputs(&sections); staticOutputs != nil {
+			terraformOutputsCache.Store(stackSlug, staticOutputs)
+			value, exists, resultErr := GetStaticRemoteStateOutput(atmosConfig, component, stack, staticOutputs, output)
+			if resultErr != nil {
+				u.PrintfMessageToTUI(terminal.EscResetLine+"%s %s\n", theme.Styles.XMark, message)
+				return nil, false, resultErr
+			}
+			u.PrintfMessageToTUI(terminal.EscResetLine+"%s %s\n", theme.Styles.Checkmark, message)
```
Comment (osterman) [inline pkg/terraform/output/executor.go]: Replace with `ui` method.

File: pkg/terraform/output/executor.go [hunk 8]
```diff
@@ -294,7 +294,110 @@ func (e *Executor) GetOutput(
...
+		return nil, false, wrapDescribeError(component, stack, err)
+	}
+
+	// Check for static remote state backend.
+	if e.staticRemoteStateGetter != nil {
+		if staticOutputs := e.staticRemoteStateGetter.GetStaticRemoteStateOutputs(&sections); staticOutputs != nil {
+			terraformOutputsCache.Store(stackSlug, staticOutputs)
+			value, exists, resultErr := GetStaticRemoteStateOutput(atmosConfig, component, stack, staticOutputs, output)
+			if resultErr != nil {
+				u.PrintfMessageToTUI(terminal.EscResetLine+"%s %s\n", theme.Styles.XMark, message)
```
Comment (osterman) [inline pkg/terraform/output/executor.go]: Replace with `ui` method.

File: pkg/terraform/output/config.go [hunk 9]
```diff
@@ -157,9 +159,42 @@ func extractComponentPath(atmosConfig *schema.AtmosConfiguration, sections map[s
...
+			}
+		}
+		return workdirPath, nil
+	}
+
 	return componentPath, nil
 }
 
+// isWorkdirEnabled reports whether provision.workdir.enabled is set to true in sections.
+func isWorkdirEnabled(sections map[string]any) bool {
```
Comment (osterman) [inline pkg/terraform/output/config.go]: Seems like this should be in `provisioner/workdir` package

**Comment by zack-is-cool** [comment]
---

**`fix: use unambiguous null-byte separator for terraform output cache key`**

Addressing the "curve fitted" comment on the `stackSlug` pattern. The
`fmt.Sprintf("%s-%s", stack, component)` format was already in `GetOutput` and
`GetAllOutputs` before this PR — `GetOutputWithOptions` just inherited it. That
said, it is genuinely ambiguous: stack `us-east-1-dev` + component `vpc`
produces the same string as stack `us-east-1` + component `dev-vpc`, which
would cause a cache collision and silently return wrong outputs when multiple
YAML functions fetch from different components in a single invocation. Fixed by
introducing a `stackComponentKey()` helper that joins with a null byte (`\x00`)
instead of a hyphen. Note: the on-disk workdir path uses the same `stack-component`
convention via `BuildPath`, but since (stack, component) pairs are unique per
project and changing the path format would orphan existing workdirs, we left
that as-is.

---

**`fix: replace deprecated u.PrintfMessageToTUI with ui.* methods in output executor`**

Replaced all `u.PrintfMessageToTUI(terminal.EscResetLine+...)` calls with
`ui.ClearLine()` + `ui.Success()`/`ui.Error()`. Removed the now-unused
`terminal` and `ui/theme` imports from `executor.go`.

---

**`refactor: consolidate isWorkdirEnabled into provisioner/workdir package`**

`isWorkdirEnabled` was duplicated in three packages (`output`, `source`,
`workdir`). Exported it as `IsWorkdirEnabled` from `pkg/provisioner/workdir`
and removed the copies in the other two. Worth exporting since it reflects a
core concept of the workdir package and the other packages already import it.

---

**`test: add coverage for GetOutputWithOptions error paths and store_cmd output-not-found`**

`GetOutputWithOptions` had only one happy-path test. Added tests for: cache hit,
invalid authManager type, DescribeComponent error, execute error, and static
remote state success path. Also added `TestStoreCommand_GetOutputValue_OutputNotFound`
to cover the `exists=false` branch in `store_cmd.go` that was flagged by CodeCov
(patch coverage was 73.79%, below the 80% threshold).

---

**`fix: address remaining CodeRabbit feedback`**

- `hook.go`: completed the truncated `MatchesEvent` doc comment
- `hooks_test.go`: replaced loose `assert.NotEmpty` checks with exact assertions
  on the store key (`"stack/comp/label_id"`) and value (`"literal-value"`)
- `executor_test.go`: added deferred cache cleanup in `TestExecutor_GetOutputWithOptions_SkipInit`

---

**`fix: use static error sentinel in fetchAndCacheOutputs execute failure`**

`fetchAndCacheOutputs` was still using a bare `fmt.Errorf` for the execute
failure path — the last remaining dynamic error in the file. Replaced with
`errUtils.Build(ErrTerraformOutputFailed)` to match the pattern used in
`GetOutput` and `GetOutputWithOptions`.

---

File: pkg/terraform/output/executor.go (hunk 3 above)
Comment (zack-is-cool) [reply pkg/terraform/output/executor.go]: claude:

> ---
> 
> **`fix: use unambiguous null-byte separator for terraform output cache key`**
> 
> Addressing the "curve fitted" comment on the `stackSlug` pattern. The
> `fmt.Sprintf("%s-%s", stack, component)` format was already in `GetOutput` and
> `GetAllOutputs` before this PR — `GetOutputWithOptions` just inherited it. That
> said, it is genuinely ambiguous: stack `us-east-1-dev` + component `vpc`
> produces the same string as stack `us-east-1` + component `dev-vpc`, which
> would cause a cache collision and silently return wrong outputs when multiple
> YAML functions fetch from different components in a single invocation. Fixed by
> introducing a `stackComponentKey()` helper that joins with a null byte (`\x00`)
> instead of a hyphen. Note: the on-disk workdir path uses the same `stack-component`
> convention via `BuildPath`, but since (stack, component) pairs are unique per
> project and changing the path format would orphan existing workdirs, we left
> that as-is.
> 
> ---

**Comment by zack-is-cool** [comment]
@coderabbitai review me

**Review by aknysh — APPROVED** [review]
