### PR TITLE
fix: propagate templates.settings.env to gomplate datasources

### LINKED ISSUE #2083: Gomplate datasources cannot access AWS credentials from template environment variables or Atmos auth
### Description

Gomplate datasources (specifically `aws+smp://` for AWS Systems Manager Parameter Store) cannot access AWS credentials, even when credentials are properly configured in `settings.templates.settings.env` or when Atmos auth is successfully authenticated. This issue does not exist in **v1.201.0**

  The datasource execution context appears isolated from:
  1. Template environment variables set in `atmos.yaml`
  2. Atmos auth-managed credentials (keyring)
  3. Shell environment variables

 ### Configuration

  **atmos.yaml:**
  ```yaml
  auth:
    logs:
      level: Trace
    providers:
      aws-sso:
        kind: aws/iam-identity-center
        region: us-east-1
        start_url: https://d-xxxxxxxxxx.awsapps.com/start
        session:
          duration: 12h
    identities:
      admin:
        kind: aws/assume-role
        default: true
        via:
          provider: aws-sso
        principal:
          assume_role: arn:aws:iam::123456789012:role/AdminRole
        spec:
          region: us-east-1

  settings:
    templates:
      settings:
        env:
          AWS_REGION: us-east-1
          AWS_PROFILE: admin
        gomplate:
          timeout: 10

  templates:
    settings:
      enabled: true
      evaluations: 1
      gomplate:
        enabled: true
        timeout: 10


# Stack configuration with datasource:
  components:
    terraform:
      example-component:
        settings:
          templates:
            settings:
              gomplate:
                timeout: 10
                datasources:
                  datadog_api_key:
                    url: aws+smp:///myapp/prod/datadog/api_key
        vars:
          datadog_api_key: '{{ (datasource "datadog_api_key").Value }}'
```
The datasource fails with NoCredentialProviders error:
Error: template: templates-all-atmos-sections:1592:24: executing "templates-all-atmos-sections" at <datasource "datadog_api_key">: error calling datasource: Couldn't read datasource 'datadog_api_key': Error reading
  aws+smp from AWS using GetParameter with input {
    Name: "/myapp/prod/datadog/api_key",
    WithDecryption: true
  }: NoCredentialProviders: no valid providers in chain
  caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
  SharedCredsLoad: failed to load profile, .
  EC2RoleRequestError: no EC2 instance role found
  caused by: RequestError: send request failed
  caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down

### Expected Behavior

  The gomplate datasource should use AWS credentials from one of:
  - The authenticated Atmos auth identity
  - Environment variables set in settings.templates.settings.env
  - The AWS credential chain (profiles, environment, etc.)

### Steps to Reproduce

1. Configure Atmos auth with AWS IAM Identity Center or assume role identities
2. Successfully authenticate: atmos auth login --identity admin
3. Verify auth works: atmos auth whoami (shows authenticated identity)
4. Configure datasources in stack YAML using aws+smp:// URLs
5. Configure AWS environment variables in settings.templates.settings.env
6. Run atmos terraform plan <component> -s <stack>

### Screenshots

_No response_

### Environment

  - **Atmos version:** 1.201.0
  - **Operating System:** macOS (darwin/arm64)
  - **AWS Region:** us-east-1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aknysh**
## what

- Fixed three interconnected bugs that prevented `templates.settings.env` from propagating environment variables to gomplate datasources
- `mapstructure:"-"` tag on `TemplatesSettings.Env` silently dropped the env field during the encode/decode/merge pipeline in `ProcessTmplWithDatasources`
- Viper lowercased env var keys (e.g., `AWS_PROFILE` → `aws_profile`) and `caseSensitivePaths` didn't include `templates.settings.env`
- Stack manifest env vars were dropped at 4 caller decode sites in `utils.go` and `describe_stacks.go`
- Added deferred env cleanup to restore original env values after template processing, preventing pollution across components
- Updated dependency compatibility (`gocloud.dev`, `terraform-exec`) after go.mod update

## why

- Users configuring `templates.settings.env` with AWS credentials (e.g., `AWS_PROFILE`, `AWS_REGION`) expected gomplate datasources (S3, SSM, Secrets Manager) to use those credentials, but env vars were never set in the OS environment
- The `os.Setenv` loop in `ProcessTmplWithDatasources` never executed because `templateSettings.Env` was always nil after mapstructure dropped it
- Without env cleanup, env vars set for one component could leak into subsequent component processing

## references

- Closes #2083
- Fix document: `docs/fixes/2026-02-16-gomplate-datasource-env-vars.md`

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed environment variable propagation in template datasources—vars from config and stack manifests are preserved during template processing.
  * Improved case sensitivity handling for template environment variables.
  * Removed an unnecessary debug log line.

* **New Features**
  * Terraform workspace selection accepts optional parameters.

* **Documentation**
  * Added docs describing datasource environment variable propagation and the fix.

* **Tests**
  * Added integration and unit tests covering env propagation and case sensitivity.

* **Chores**
  * Updated dependency licenses/versions and NOTICE entries.
  * Component describe outputs now include a new deprecated field placeholder.

### CODE REVIEW

File: internal/exec/utils.go [hunk 1]
```diff
@@ -734,6 +734,11 @@ func ProcessStacks(
 			return configAndStacksInfo, err
 		}
 
+		// Restore env vars that mapstructure:"-" dropped during Decode.
+		if envMap := extractEnvFromRawMap(configAndStacksInfo.ComponentSettingsSection); len(envMap) > 0 {
+			settingsSectionStruct.Templates.Settings.Env = envMap
```
Comment (osterman) [inline internal/exec/utils.go:739]: There are functions or code that already handle how to work with key sensitive environment, variables in Viper. I haven't looked closely at what you're doing here. I just wanna make sure we're not duplicating that effort. Or if we are then we should be clear on why it's necessary.

I can't recall entirely, but there's an env manager introduced his part of support for global ENV.

Comment (aknysh) [reply internal/exec/utils.go:739]: Great question — this is **not** duplicating the existing case-sensitive env handling. These solve two completely different problems at different stages of the config pipeline:

### Problem 1: Viper lowercases keys (existing `casemap` infrastructure)
Viper lowercases all YAML map keys, so `AWS_PROFILE` becomes `aws_profile`. The existing `caseSensitivePaths` + `GetCaseSensitiveMap` + `casemap.ApplyCase` mechanism fixes this — the data is **present** but with **wrong case**. We extended this system in this PR by adding `"templates.settings.env"` to `caseSensitivePaths` in `load.go`.

### Problem 2: `mapstructure:"-"` drops the entire Env field (new `extractEnvFromRawMap`)
The `TemplatesSettings.Env` field has `mapstructure:"-"` tag ([schema.go:418](https://github.com/cloudposse/atmos/blob/main/pkg/schema/schema.go#L418)) to avoid a type collision with `Command.Env` (which is `[]CommandEnv`, a different type). This causes `mapstructure.Decode()` to **silently discard the entire Env field** — the data is completely **absent**, not just mis-cased.

In `ProcessTmplWithDatasources`, the template settings go through:
1. `mapstructure.Decode(struct -> map)` — Env dropped
2. `u.MergeMaps(map1, map2)` — merging, but Env is already gone
3. `mapstructure.Decode(map -> struct)` — Env still absent

The `extractEnvFromRawMap` function recovers Env from the **raw `map[string]any`** source before mapstructure discards it. The existing `casemap`/`GetCaseSensitiveMap` system cannot help here because it operates on the struct fields (which are already empty after decode).

### Why not remove `mapstructure:"-"`?
We can't remove it because `mapstructure` would fail — `TemplatesSettings.Env` is `map[string]string` but `Command.Env` is `[]CommandEnv`, and mapstructure treats all `env` keys the same during recursive decoding.

### Summary
| Mechanism | Problem | Data State | Where it acts |
|---|---|---|---|
| `casemap`/`GetCaseSensitiveMap` | Viper lowercases keys | Present, wrong case | After Viper load |
| `extractEnvFromRawMap` | `mapstructure:"-"` drops field | Completely absent | Before/after mapstructure.Decode |

Both are needed. Happy to add a code comment clarifying this distinction if that would help.
