### PR TITLE
fix: MCP server env block not applied to auth setup; consolidate env primitives in pkg/env and pkg/auth

### LINKED ISSUE #2283: ATMOS_PROFILE environment variable set in mcp.yaml env block is not used during MCP server auth setup
### Describe the Bug

When configuring an MCP server in .atmos.d/mcp.yaml with ATMOS_PROFILE set under the env key, the value is not picked up during the auth setup phase. The server fails to start with identity not found: core-root/terraform, which indicates the identity lookup is happening without the managers profile context. The same identity resolves correctly when ATMOS_PROFILE is exported directly in the shell.

The env block in mcp.yaml should inject environment variables into the server process, but it appears the auth setup runs before these variables are applied, causing identity resolution to fail.

### Expected Behavior

Setting ATMOS_PROFILE in the env block of a server definition in mcp.yaml should make it available during the full server lifecycle, including the auth/identity resolution phase. The server should start successfully the same way it would if ATMOS_PROFILE were exported in the shell before running the command.

### Steps to Reproduce

1. Configure .atmos.d/mcp.yaml with a server that sets ATMOS_PROFILE under env:
yaml
```
mcp:
  enabled: true
  servers:
    atmos:
      description: Atmos MCP server
      command: atmos
      args: ["mcp", "start"]
      env:
        ATMOS_PROFILE: managers
      identity: core-root/terraform
```
2. Run the MCP test command:
```
atmos mcp test atmos
```
3. Observe the error:
```
✗ Server failed to start
   Error: MCP server failed to start: atmos: auth setup failed for "atmos": identity not found:  core-root/terraform
```
4. As a workaround, export the variable in the shell first:
```
export ATMOS_PROFILE=managers
atmos mcp test atmos
```

### Screenshots

_No response_

### Environment

•  Atmos version: 1.214.0
•  OS: macOS (darwin/arm64)

### Additional Context

The env variables defined in mcp.yaml seem to be applied after the identity/auth resolution step rather than before it. The auth setup needs the profile context to locate the identity core-root/terraform, but since ATMOS_PROFILE from the env block isn't set yet at that point, the identity lookup fails against the default (empty) profile.

### PR DESCRIPTION
**Pull request by aknysh**
## what

- **Bug fix:** External MCP servers configured with both `identity:` and an `env:` block containing `ATMOS_*` variables (e.g. `ATMOS_PROFILE`, `ATMOS_CLI_CONFIG_PATH`, `ATMOS_BASE_PATH`) failed auth setup with `identity not found`. The parent's auth manager was built once from `os.Environ()` and never saw the server's `env:` block.
- **Architectural cleanup driven by review feedback:**
  - New foundational primitive `env.SetWithRestore` in `pkg/env` (atmos already has a dedicated env package; four other local save/set/restore variants exist and should consolidate to this in a follow-up).
  - New high-level primitive `auth.CreateAndAuthenticateManagerWithEnvOverrides` in `pkg/auth` that delegates env mutation to `pkg/env` and composes `cfg.InitCliConfig` + `auth.CreateAndAuthenticateManagerWithAtmosConfig`.
  - Thin MCP-specific adapter `mcpclient.ScopedAuthProvider` (~85 lines) that implements a new `PerServerAuthProvider` interface so `WithAuthManager` dispatches per-server.
  - **Canonical Atmos env-var namespace constants** (`AtmosEnvVarNamespace`, `AtmosEnvVarPrefix`) added to `pkg/config/const.go` with build-time invariant tests. Migrated five hardcoded `\"ATMOS\"` / `\"ATMOS_\"` literals scattered across `cmd/root.go`, `cmd/auth_validate.go`, `pkg/auth`, and `pkg/ai/agent/codexcli` to use them.
- **Result for users:** any external MCP server can now define `ATMOS_PROFILE` (or any other `ATMOS_*` variable) in its `env:` block and have it influence identity resolution — including configurations that run `atmos mcp start` itself as an external MCP server (the original report).

## why

- The auth manager was being constructed once at command startup using the parent's `os.Environ()`. Server `env:` blocks were only applied to the spawned subprocess via `cmd.Env`, so the parent's identity lookup ran against the *default* profile and never saw `ATMOS_PROFILE: managers` (or any other override). The user's only workaround was exporting the variable in the shell before running atmos.
- The bug surfaces most visibly when a user configures `atmos mcp start` itself as an external MCP server (the original report), but it affects **any** external MCP server with both `identity:` and `env: ATMOS_*: ...`.
- The fix lives entirely on the client side. The Atmos MCP server (`cmd/mcp/server`) was already correct: when spawned as a subprocess it inherits the merged env (`os.Environ()` + `env:` block) and `cfg.InitCliConfig` reads `ATMOS_*` from there.
- **Why the architectural cleanup:** review feedback flagged that (a) putting per-command auth factories in `cmd/` is a slippery slope, (b) `pkg/auth` shouldn't re-implement env mutation when `pkg/env` already exists, and (c) defining what counts as an Atmos env variable inside any specific subsystem is the wrong layering. Each round of feedback pushed the primitives down to where they belong, and the result is significantly less code with cleaner layering.

## layering after this PR

\`\`\`
pkg/config       ← AtmosEnvVarNamespace / AtmosEnvVarPrefix (single source of truth)
pkg/env          ← SetWithRestore (foundational env primitive, no policy)
  ↑
pkg/auth         ← CreateAndAuthenticateManagerWithEnvOverrides (composes pkg/env + cfg.InitCliConfig + auth)
  ↑
pkg/mcp/client   ← ScopedAuthProvider (thin MCP adapter, ~85 lines)
  ↑
cmd/mcp/client,  ← one-line consumers, zero auth-factory code
cmd/ai
\`\`\`

## test coverage

100% on every new function:
- \`pkg/env/restore.go\` → \`SetWithRestore\` (incl. setenv-error branch via injectable hook)
- \`pkg/auth/manager_env_overrides.go\` → \`CreateAndAuthenticateManagerWithEnvOverrides\` (incl. env-hook error branch via injectable hook), \`filterAtmosOverrides\` (table-driven)
- \`pkg/mcp/client/scoped_auth.go\` → \`NewScopedAuthProvider\`, \`ForServer\`, \`PrepareShellEnvironment\`
- \`pkg/mcp/client/session.go\` → \`WithAuthManager\` (incl. per-server dispatch branch)
- \`cmd/mcp/client/start_options.go\` → \`buildAuthOption\`, \`mcpServersNeedAuth\`
- \`cmd/ai/init.go\` → \`resolveAuthProvider\`
- \`pkg/config/const_test.go\` → invariant tests for the canonical constants

## references

- closes #2283
- See \`docs/fixes/2026-04-06-mcp-server-env-not-applied-to-auth-setup.md\` for full root-cause analysis, the fixed flow diagram, the test plan, and a follow-up consolidation note for the four pre-existing local save/restore env helpers (\`internal/exec.setEnvVarsWithRestore\`, \`pkg/auth/cloud/gcp.PreserveEnvironment/RestoreEnvironment\`, \`pkg/telemetry.PreserveCIEnvVars/RestoreCIEnvVars\`, \`pkg/auth/identities/aws.setupAWSEnv\`) that should migrate to \`env.SetWithRestore\` in a separate PR.
- Related: \`docs/fixes/2026-03-25-describe-affected-auth-identity-not-used.md\` (another auth-context propagation fix in a different code path).
- Related PRD: \`docs/prd/atmos-mcp-integrations.md\` (overall MCP client architecture).

## Summary by CodeRabbit

* **New Features**
  * Per-server authentication scoping for MCP so each server can use its own ATMOS env during auth.
  * Canonical ATMOS env namespace/prefix and safer env-override handling during auth setup.

* **Bug Fixes**
  * MCP server ATMOS env values are now applied during authentication setup.
  * Clearer error mapping when per-server auth is unavailable.

* **Documentation**
  * Added doc describing the auth env propagation fix and behavior.

* **Tests**
  * Extensive unit tests for per-server auth, env overrides/restoration, and related flows.

### CODE REVIEW

File: cmd/mcp/client/auth_factory.go
Comment (osterman) [inline cmd/mcp/client/auth_factory.go:1]: Why does MCP have its own auth factory? Seems like a slippery slope. Why wouldn't then each other subcommand have a factory for auth?

File: pkg/mcp/client/env_overrides.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+// in a server's `env:` block influence atmos config loading and identity
+// resolution — even though the auth setup runs in the parent process before
+// the subprocess is spawned.
+//
+// The returned restore function is idempotent. Callers should `defer restore()`.
+//
+// Note: this function is intentionally NOT goroutine-safe. Callers must
+// serialize calls when multiple servers are being authenticated concurrently.
+// In current usage MCP servers are started sequentially, so this is fine.
+func ApplyAtmosEnvOverrides(env map[string]string) func() {
```
Comment (osterman) [inline pkg/mcp/client/env_overrides.go]: We already have a lot of functions just for managing environments. In fact, we have a whole environment package. Why is this implementing its own environment handling?

File: pkg/mcp/client/env_overrides.go [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+import (
+	"os"
+	"sort"
+	"strings"
+
+	"github.com/cloudposse/atmos/pkg/perf"
+)
+
+// AtmosEnvPrefix is the prefix used to identify Atmos environment variables.
+const AtmosEnvPrefix = "ATMOS_"
```
Comment (osterman) [inline pkg/mcp/client/env_overrides.go]: If we're defining the prefix for atmos environment variables in this file, deep, deep inside of this MCP client package, something seems off.

File: cmd/mcp/client/auth_factory.go
Comment (aknysh) [reply cmd/mcp/client/auth_factory.go:1]: Good call — you were right to push back. I just pushed a refactor that moves the auth primitives down into pkg/auth where they belong, matching the precedent we already set for other auth work.
                                                                                                                                                                                                                                                    
  What moved to pkg/auth                                                                                  
                                                                                                                                                                                                                                                    
  Two new files, both reusable by any subsystem — nothing about them is MCP-specific:                                                                                                                                                               
                                                                                                                                                                                                                                                    
  - pkg/auth/env_overrides.go → ApplyAtmosEnvOverrides(map[string]string) func(). Temporarily applies ATMOS_* variables to os.Environ() and returns a restore closure. Only touches ATMOS_* keys, idempotent restore, sequential by design          
  (documented).                                                                                           
  - pkg/auth/manager_env_overrides.go → CreateAndAuthenticateManagerWithEnvOverrides(overrides map[string]string) (AuthManager, error). A high-level primitive that composes the existing pieces: apply overrides → cfg.InitCliConfig →             
  CreateAndAuthenticateManagerWithAtmosConfig → restore. Returns (nil, nil) under the same contract as the existing WithAtmosConfig variant, so callers that require a manager check explicitly.                                                    
   
  Any future subsystem that needs "authenticate against a config variant without mutating the parent process" — eks-kubeconfig, describe-affected, terraform backend reads, whatever — now has it in one call instead of reinventing it.            
                                                                                                          
  What stayed in pkg/mcp/client                                                                                                                                                                                                                     
                                                                                                          
  Only the MCP-specific glue. ScopedAuthProvider is now a ~85-line adapter whose entire job is:                                                                                                                                                     
   
  1. Satisfy the two pkg/mcp/client-local interfaces (AuthEnvProvider, PerServerAuthProvider).                                                                                                                                                      
  2. Plumb ParsedConfig.Env into auth.CreateAndAuthenticateManagerWithEnvOverrides.                       
  3. Convert (nil, nil) into errUtils.ErrMCPServerAuthUnavailable wrapped with server + identity context so callers can errors.Is-match and display actionable info.                                                                                
                                                                                                                                                                                                                                                    
  No reimplementation of auth primitives. pkg/mcp/client doesn't even import pkg/config anymore — just pkg/auth.                                                                                                                                    
                                                                                                                                                                                                                                                    
  What's gone                                                                                                                                                                                                                                       
                                                                                                          
  - pkg/mcp/client/env_overrides.go (+test) — moved to pkg/auth/.                                                                                                                                                                                   
  - cmd/mcp/client/auth_factory.go (+test) — deleted (was the duplicate you were reacting to).
  - The duplicate perServerAuthProvider struct inside cmd/ai/init.go — deleted.                                                                                                                                                                     
                                                                                                                                                                                                                                                    
  Both call sites in cmd/ are now one line:                                                                                                                                                                                                         
                                                                                                                                                                                                                                                    
  mcpclient.WithAuthManager(mcpclient.NewScopedAuthProvider(atmosConfig))                                                                                                                                                                           
                                                                                                                                                                                                                                                    
  Zero auth-factory code lives in cmd/.
                                                                                                                                                                                                                                                    
  Layering                                                                                                                                                                                                                                          
   
  pkg/auth                 ← owns env-override + manager primitives                                                                                                                                                                                 
    ↑                                                                                                                                                                                                                                               
  pkg/mcp/client           ← thin adapter (PerServerAuthProvider + ParsedConfig glue)
    ↑                                                                                                                                                                                                                                               
  cmd/mcp/client, cmd/ai   ← one-liner consumers                                                          
                                                                                                                                                                                                                                                    
  No circular deps. pkg/auth already depended on pkg/config, so the new primitives fit naturally.                                                                                                                                                   
                                                                                                                                                                                                                                                    
  Coverage                                                                                                                                                                                                                                          
                                                                                                          
  100% on everything new in both pkg/auth and pkg/mcp/client/scoped_auth.go. Test semantics for env-override, config-reload, and manager construction live in pkg/auth where the logic lives; the MCP adapter tests only cover the adapter's        
  contract (plumbing, sentinel wrapping) and stub the builder directly to avoid cross-package coupling.
                                                                                                                                                                                                                                                    
  Net diff                                                                                                

  –594 lines vs. my previous commit, while gaining reusable primitives. Shorter, more correct layering, and the next time someone needs scoped auth in a non-MCP context they won't copy-paste anything — they'll call                              
  auth.CreateAndAuthenticateManagerWithEnvOverrides.

File: pkg/mcp/client/env_overrides.go (hunk 1 above)
Comment (aknysh) [reply pkg/mcp/client/env_overrides.go]: You were right on both counts — pkg/env exists (I missed it), and we're already proliferating env-handling helpers. Just refactored to address both.

  What I found while validating your comment

  pkg/env is a comprehensive package for env handling — Builder, MergeSystemEnv*, EnvironToMap, formatters, etc. It just didn't have a save/set/restore primitive. Worse, I found four existing local implementations of exactly that idea, none sharing code.

  My ApplyAtmosEnvOverrides was the fifth reinvention. That's exactly the proliferation you flagged.

  What I changed

  1. Added env.SetWithRestore(vars map[string]string) (func(), error) to pkg/env/restore.go. Generic save/set/restore primitive — no key filter, no policy. Returns idempotent cleanup, cleanup is non-nil even on partial failure so callers can
  defer cleanup() safely. Fully covered including the setenv-error path (via an injectable setenvFn hook).

  2. Deleted pkg/auth/env_overrides.go — my redundant ATMOS-specific helper.

  3. Updated pkg/auth.CreateAndAuthenticateManagerWithEnvOverrides to call env.SetWithRestore instead of doing its own env mutation. The ATMOS_*-prefix filter is now a 5-line filterAtmosOverrides helper at the caller, where the policy belongs —
   pkg/env's primitive stays generic.

  4. Tests: 8 new tests in pkg/env/restore_test.go and 4 added to pkg/auth/manager_env_overrides_test.go (filter behavior, env-hook error path, defensive nil-cleanup guard, table-driven filterAtmosOverrides). 100% coverage on every new function
   — every branch including the setenv-error paths.

  Final layering

  pkg/env                 ← SetWithRestore (foundational, generic)
    ↑
  pkg/auth                ← CreateAndAuthenticateManagerWithEnvOverrides
    │                       (filters ATMOS_*, calls env.SetWithRestore)
    ↑
  pkg/mcp/client          ← ScopedAuthProvider (thin MCP adapter)
    ↑
  cmd/mcp/client, cmd/ai  ← one-line consumers

  Zero env-mutation logic in cmd/. Zero env-mutation logic in pkg/mcp/client. Even pkg/auth doesn't mutate env directly anymore — it delegates to pkg/env.

  Follow-up scope (deliberately not in this PR)

  The fix doc now documents that the four pre-existing helpers above should migrate to env.SetWithRestore in a separate PR. SetWithRestore is intentionally generic enough that all four migrations are mechanical:

  1. internal/exec.setEnvVarsWithRestore (smallest, lowest risk — start here)
  2. pkg/telemetry.PreserveCIEnvVars / RestoreCIEnvVars
  3. pkg/auth/identities/aws.setupAWSEnv
  4. pkg/auth/cloud/gcp.PreserveEnvironment / RestoreEnnvironment

  I kept that out of this PR because it touches four unrelated subsystems and would balloon the diff beyond the original bug fix.

File: pkg/mcp/client/env_overrides.go (hunk 2 above)
Comment (aknysh) [reply pkg/mcp/client/env_overrides.go]: You're right — and even after I moved it to pkg/auth in the previous round, that's still the wrong place. The canonical "what counts as an Atmos environment variable" is a global Atmos identity concept, not an auth concern. Just refactored.
                                                                                                                                                                                                                                                    
  What I found                                                                                            
                                                                                                                                                                                                                                                    
  There was no canonical exported constant for the Atmos env namespace anywhere in the codebase. Every place that needed it hardcoded a literal:                                                                                                    
   
  - cmd/root.go:1658 → viper.SetEnvPrefix("ATMOS")                                                                                                                                                                                                  
  - cmd/auth_validate.go:65 → viper.SetEnvPrefix("ATMOS") (duplicate)                                     
  - pkg/auth/manager_env_overrides.go → const AtmosEnvPrefix = "ATMOS_" (my constant, wrong package)                                                                                                                                                
  - pkg/ai/agent/codexcli/client.go:281 → strings.HasPrefix(env, "ATMOS_")                                                                                                                                                                          
  - pkg/ai/agent/codexcli/client_test.go:333 → "ATMOS_"                                                                                                                                                                                             
                                                                                                                                                                                                                                                    
  Five separate places, no shared definition. So your concern wasn't just where my constant lived — there was a deeper proliferation.                                                                                                               
                                                                                                                                                                                                                                                    
  What I changed                                                                                                                                                                                                                                    
                                                                                                          
  Single source of truth in pkg/config/const.go (next to AtmosCommand, CliConfigFileName, etc. — the foundational config package every other package already depends on):                                                                           
   
  AtmosEnvVarNamespace = "ATMOS"                       // for viper.SetEnvPrefix                                                                                                                                                                    
  AtmosEnvVarPrefix    = AtmosEnvVarNamespace + "_"    // for HasPrefix checks                                                                                                                                                                      
                                                                                                                                                                                                                                                    
  The prefix is derived from the namespace, so they cannot drift.                                                                                                                                                                                   
                                                                                                                                                                                                                                                    
  Build-time invariant tests in pkg/config/const_test.go:                                                                                                                                                                                           
  1. TestAtmosEnvVarPrefixMatchesNamespace — fails the build if anyone ever sets AtmosEnvVarPrefix to something that's not AtmosEnvVarNamespace + "_".
  2. TestAtmosEnvVarConstants_Values — locks in the literal values "ATMOS" and "ATMOS_". The Atmos env namespace is part of the public contract — silently changing it would break every user with ATMOS_* env vars set, so I want a renamer to trip
   a test, not a release.                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                    
  Migrated all five call sites                                                                       
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                          
  Verified with grep "ATMOS_" and grep 'SetEnvPrefix("ATMOS")' — zero remaining literals in any migrated file. Build, vet, and tests all green.                                                                                                     
                                                                                                          
  Out of scope (deliberately)                                                                                                                                                                                                                       
                                                                                                          
  I did not sweep the t.Setenv("ATMOS_GITHUB_TOKEN", ...) / os.Getenv("ATMOS_REDIS_URL") literals scattered across pkg/toolchain, pkg/github, pkg/store, pkg/xdg, etc. Those are specific env-var names, not the prefix itself, so they don't share 
  the concern you raised. There are dozens of them, and they each need their own constant for the full var name (AtmosGitHubTokenEnvVar, AtmosRedisURLEnvVar, etc.) — that's a separate cleanup PR worth doing on its own merits if you want me to
  file an issue.                                                                                                                                                                                                                                    
                                                                                                          
  What you specifically pointed at — the namespace/prefix as a policy definition — is now exactly one line in pkg/config/const.go, with two invariant tests to keep it that way.
