### PR TITLE
fix: Describe Affected Detects Component File Changes. fix: Vendored components with `source`

### LINKED ISSUE #1978: atmos describe affected: does not consider component changes
### Describe the Bug

`atmos describe affected` seems to only consider stack changes, but not component changes.

### Expected Behavior

According to the doc, component changes should have affected stacks listed too.

### Steps to Reproduce

```plain
$ diff -r --exclude=.git . /tmp/ref
diff -r '--exclude=.git' ./atmos_test/components/terraform/second_component/main.tf /tmp/ref/atmos_test/components/terraform/second_component/main.tf
1c1
< resource "terraform_data" "display_message_modified" {
---
> resource "terraform_data" "display_message" {


$ atmos describe affected --repo-path /tmp/ref
[]
```

Of course, in this example, `second_component` is referenced in my stacks:
```plain
$ atmos list instances
 Component         Stack 
─────────────────────────
 myapp             dev   
 myapp             prod  
 second_component  dev   
 second_component  prod  
```

### Screenshots

_No response_

### Environment

Atmos 1.204.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aknysh**
## what

- Fixed `atmos describe affected` to correctly detect component file changes (Terraform, Helmfile, Packer)
- Added `gitRepoRoot` parameter to path resolution logic to properly resolve relative paths from git diff
- Fixed detection of components using `source` for vendoring (components without explicit `component` field)
- A regression in previous Atmos releases caused changes to component files to not be detected in certain scenarios

### Issue 1: Git repo root path resolution
- Git diff returns file paths relative to the git repository root
- The previous implementation used `filepath.Abs()` which resolves paths against the current working directory
- When Atmos was run from a subdirectory (e.g., `atmos -C examples/demo-stacks`), paths would not match, causing component changes to go undetected

### Issue 2: Vendored components with `source`
- Components using `source` for just-in-time vendoring were not being detected
- The affected detection required an explicit `component` field to determine which folder to monitor
- Now defaults to using the component name (YAML key) when no explicit `component` field is specified

### Path resolution fix
- `newChangedFilesIndex()` now accepts `gitRepoRoot` parameter
- Relative paths from git diff are resolved against the git repo root, not the current working directory

### Source component detection fix
- Added `GetComponentFolder()` helper in `stack_utils.go` to consolidate component folder resolution logic
- Modified `BuildComponentPath()` to accept optional fallback parameter
- `processTerraformComponentsIndexed()`, `processHelmfileComponentsIndexed()`, `processPackerComponentsIndexed()` now use `GetComponentFolder()` which defaults to component name when `component` field is missing
- This ensures components with `source` vendoring are properly tracked

## test coverage

All three scenarios are covered by unit tests:

| Scenario | Test Coverage |
|----------|---------------|
| **`metadata.component` specified** | `TestFindAffectedComponentFolderChanges/explicit_component_field` ✓<br>`TestFindAffectedComponentFolderChanges/inherited_base_component` ✓<br>`TestGetComponentFolder/returns_explicit_component_field_when_set` ✓ |
| **`source` specified (JIT vendoring)** | `TestFindAffectedComponentFolderChanges/JIT_vendored_component_with_source_-_simple_config` ✓<br>`TestFindAffectedComponentFolderChanges/JIT_vendored_component_with_source_-_full_config` ✓<br>`TestFindAffectedHelmfileAndPackerComponents/Helmfile_JIT_vendored_with_source` ✓<br>`TestFindAffectedHelmfileAndPackerComponents/Packer_JIT_vendored_with_source` ✓ |
| **`source` + `workdir` specified** | `TestFindAffectedHelmfileAndPackerComponents/Terraform_with_source_and_workdir` ✓<br>`TestFindAffectedHelmfileAndPackerComponents/Helmfile_with_source_and_workdir` ✓<br>`TestFindAffectedHelmfileAndPackerComponents/Packer_with_source_and_workdir` ✓ |

### Resolution flow

1. **`metadata.component: mock`** → Stack processing sets `componentSection["component"] = "mock"` → `GetComponentFolder` uses that value
2. **`source` only** → No `component` field → `GetComponentFolder` falls back to componentName (YAML key)
3. **`source` + `workdir`** → Same as 2 (see note below)

### Why `provision.workdir` doesn't affect folder resolution

For `describe affected`, the workdir configuration doesn't change how component folders are resolved because:

1. **Workdir is runtime-only**: The `.workdir/` directory is created at runtime when you run `atmos terraform plan/apply`. It's a temporary copy of the component files.

2. **Workdir is not tracked in git**: The `.workdir/` directory is in `.gitignore`. Changes to files in `.workdir/` don't appear in `git diff`.

3. **`describe affected` compares git branches**: It looks at what files changed between commits/branches. Since workdir files aren't tracked, the detection happens on the **source** files:
   - For local components: `components/terraform/<component>/`
   - For vendored components with `source`: `components/terraform/<component-name>/` (where files are vendored)

```
Source of truth (tracked in git)     →    Workdir (runtime, not tracked)
components/terraform/vpc-remote/     →    .workdir/terraform/dev-vpc-remote/
         ↑                                           ↑
   describe affected                          terraform runs here
   detects changes HERE
```

When you modify vendored component files in `components/terraform/vpc-remote-workdir/`, `describe affected` detects that change. The fact that at runtime those files get copied to `.workdir/` doesn't matter for change detection.

## references

- Closes #1978
- [Vendoring Documentation](https://atmos.tools/vendor/)
- [Source Configuration](https://atmos.tools/vendor/config/sources/)
- [Just-in-Time Vendoring](https://atmos.tools/cli/commands/terraform/source/)

## Summary by CodeRabbit

* **Bug Fixes**
  * Corrected affected-component detection when running from a repo root or subdirectory (e.g., using -C), improving path resolution.
  * Properly detect vendored (source-based) components and component folder/file changes across Terraform, Helmfile, and Packer.
* **Documentation**
  * Added blog posts explaining the improved detection, vendoring behavior, and cross-platform path-handling guidance.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/exec/describe_affected_components.go [hunk 1]
```diff
@@ -314,18 +326,23 @@ func processPackerComponentsIndexed(
 			}
 		}
 
-		if component, ok := componentSection[cfg.ComponentSectionName].(string); ok && component != "" {
-			changed, err := isComponentFolderChangedIndexed(component, cfg.PackerComponentType, atmosConfig, filesIndex, patternCache)
+		// Determine the component folder path.
```
Comment (osterman) [inline internal/exec/describe_affected_components.go]: We have a function to resolve the component path. We should have a single code path for this.

**Comment by aknysh** [comment]
@coderabbitai full review please

File: website/blog/2025-01-21-describe-affected-component-detection.mdx [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+title: 'Fixed: Describe Affected Now Detects Component File Changes'
+authors:
+  - aknysh
+tags:
+  - bugfix
+date: 2025-01-21T00:00:00.000Z
+---
+
+Atmos now correctly detects component file changes when running `atmos describe affected`.
+A regression in previous Atmos releases caused changes to Terraform, Helmfile, or Packer component files to not be detected in certain scenarios.
```
Comment (osterman) [inline website/blog/2025-01-21-describe-affected-component-detection.mdx]: Can we call out in which release it broke?
