### PR TITLE
fix: Resolve assume role issues and improve error handling

### LINKED ISSUE #1030: Missing Component Results in Silent Failure
### Describe the Bug

When Atmos is unable to find a component it needs to in order to pull a value from (when utilizing !terraform.output or atmos.Component function calls), it silently fails with no log output or information of any kind, and simply returns an exit code of `1`.

### Expected Behavior

I would expect some measure of output from the binary, indicating what failed, or why, or even a stack trace to help bring the information back to Cloudposse devs for assistance.

### Steps to Reproduce

Scenario Setup: atmos w/ terraform components. Component A uses an input using the `atmos.Component` (or !terraform.output, doesn't matter) template function, pulling in an output from Component B.

Running a plan/output/apply all works as expected (proving happy normal state).

Then remove or comment out the references to Component B in its manifest (but leave state untouched, and the resources existing).

Attempt to apply/plan/output Component A again. Atmos will silently fail with no log output at all, even with ATMOS_LOGS_LEVEL=Trace or Debug.

### Screenshots

_No response_

### Environment

- OS: OSX
- Version: 15.3
- Atmos version: 1.160.0
- No module or component versions required

### Additional Context

_No response_

### LINKED ISSUE #1909: Invalid role ARN composed: Template env() values are empty when rendering assume_role
### Describe the Bug

Summary
•  When composing Terraform backend/provider assume_role.role_arn from template environment variables, the rendered ARN drops the interpolated segments and becomes invalid.
•  Variables accessed via .vars.* resolve correctly; values fetched via env "..." render as empty strings.

Impact
•  Atmos cannot assume the target role to read state or run plans, causing early failures during template evaluation.

Where it happens
•  In stacks under orgs/... (e.g., stacks/orgs/<org>/<tenant>/<stage>/_defaults.yaml) where role_arn is built like:
◦  arn:aws:iam::{{ (printf "%s_account_id" .vars.stage | env) }}:role/{{ .vars.namespace }}-{{ (env "gbl_environment") }}-{{ .vars.stage }}-{{ (printf "%s_role_suffix" .vars.stage | env) }}

### Expected Behavior

The assume_role ARN is fully rendered using the template env values, and Atmos can assume the role.

### Steps to Reproduce

I'm using terraform orgs to template the terraform roles to assume so I have in `orgs/acme/_defaults.yaml` the backend configuration like normal:
```
terraform:
  backend_type: s3
  backend:
    s3:
      encrypt: true
      use_lockfile: true
      bucket: '{{ .vars.namespace }}-gbl-root-tfstate'
      key: 'terraform.tfstate'
      region: '{{ .vars.region }}'
```

but for the backend role I have `orgs/acme/plat/_default.yaml`:
```
terraform:
  backend_type: s3
  backend:
    s3:
      assume_role:
        role_arn: 'arn:aws:iam::{{ (env "state_account_id") }}:role/{{ .vars.namespace }}-{{ (env "gbl_environment") }}-{{ (env "state_stage") }}-{{ (env "state_role_suffix") }}'
```

and for the provider role I have `orgs/acme/plat/dev/_default.yaml`:
```
terraform:
  settings:
    github:
      actions_enabled: true
  providers:
    aws:
      region: '{{ .vars.region }}'
      assume_role:
        role_arn: 'arn:aws:iam::{{ (printf "%s_account_id" .vars.stage | env) }}:role/{{ .vars.namespace }}-{{ (env "gbl_environment") }}-{{ .vars.stage }}-{{ (printf "%s_role_suffix" .vars.stage | env) }}'
```

### Screenshots

_No response_

### Environment

_No response_

### Additional Context

What I think is happening is that in the latest version the evaluation on orgs has change and is not longer getting the Environment variables on the CLI context only the .vars work there now. I think this is the issue bc the error show that is trying to assume the incorrect role and it looks like this:
```
Assuming role ARN=arn:aws:iam:::role/acme---
```
Followed by AccessDenied on sts:AssumeRole due to the invalid ARN.

### LINKED ISSUE #1921: panic: authContextWrapper.GetChain should not be called
### Describe the Bug

In version 1.202.1, with Atmos internal auth configured, the function !terraform.output is throwing exceptions when tries to create the AuthManager for one of the nested components.

### Expected Behavior

Function !terraform.output works properly without throwing exceptions

### Steps to Reproduce

- Configure AUTH (for example AWS SSO provider)
- Use !terraform.output

### Screenshots

Image

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aknysh**
## what

- Fix panic when using `!terraform.output` with authentication enabled
- Fix silent/confusing errors when referenced component is missing in template functions
- Add comprehensive documentation for env template function behavior
- Document `base_path` behavior change as a breaking change in changelog

### Issue #1921: Panic in `!terraform.output` with Authentication

When using `!terraform.output` with AWS SSO authentication, Atmos panicked with:
```
panic: authContextWrapper.GetChain should not be called
```

**Root Cause:** The `authContextWrapper.GetChain()` method was implemented as a panic stub, but the auth system evolution now calls this method during nested component resolution.

**Fix:** Changed `GetChain()` to return an empty slice instead of panicking. An empty chain means no inherited identity from the wrapper, so nested components use their own defaults.

### Issue #1030: Missing Component Results in Silent Failure

When using template functions like `atmos.Component()` or `!terraform.output` to reference components that are removed from configuration, Atmos produced confusing errors or silent failures.

**Root Cause:** The `ErrInvalidComponent` error chain was preserved when wrapping errors from `DescribeComponent`. This caused the component type fallback logic (`detectComponentType()`) to incorrectly trigger, producing misleading "component not found as Helmfile/Packer" errors instead of clear "referenced component missing" errors.

**Fix:** Added `WrapComponentDescribeError()` helper in `errors/error_funcs.go` that breaks the `ErrInvalidComponent` chain using `%v` instead of `%w` formatting, ensuring errors about referenced components are returned immediately with clear messages.

### Env Template Function Analysis (Not a Bug)

Investigated user report that `env` template function returns empty strings while `.vars.*` works correctly. Analysis confirmed this is **expected behavior**:

- The `env` function is from Sprig and calls `os.Getenv()`
- When an env var is NOT set, it returns empty string (standard Go behavior)
- `.vars.*` works because it comes from stack YAML config passed to template
- User needs to ensure env vars are set before running atmos commands
- Generated files (backend.tf.json) looking correct is from cached runs when vars WERE set

- Closes #1909 

### Document `base_path` Behavior Change

A recent Atmos CLI change (v1.202.0) altered how `base_path` is interpreted in `atmos.yaml`. Previously, `base_path: ""` was implicitly treated as the current directory. Now it triggers git root discovery.

**Impact:** Users with multiple Atmos projects in a single repo, or where the Atmos project root differs from the git root, must update their configuration:

```yaml
# Before (no longer works as expected)
base_path: ""

# After (explicit current directory)
base_path: "."
```

**Fix:** Added breaking change blog post to the changelog documenting:
- The behavior change and affected versions
- Who is affected (multi-project repos, non-git-root configs)
- Migration steps with examples
- Path resolution semantics table

## references

closes #1030
closes #1921

### Testing

1. **Unit tests:** All new functionality covered with tests
2. **Error chain verification:** Tests use `assert.NotErrorIs()` to verify chain is broken
3. **Regression test:** `TestAuthContextWrapper_GetChain_NoLongerPanics` prevents future panics
4. **Env function tests:** Document expected behavior when env vars are/aren't set

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented incorrect error propagation when describing missing components and eliminated panics during authenticated Terraform output handling, improving error stability and clarity.

* **Tests**
  * Added regression tests for component error wrapping, auth-chain behavior, and template env-var rendering (populated and unset scenarios).

* **Documentation**
  * Added a troubleshooting guide for Terraform output issues and a blog post explaining base_path behavior changes and migration guidance.

* **Diagnostics**
  * Added debug logging for YAML/template function errors.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: internal/exec/template_funcs_component_test.go [hunk 1]
```diff
@@ -89,3 +92,65 @@ func TestComponentFunc(t *testing.T) {
...
+			wantErrInvalid:  false, // Chain should be broken
+			wantMsgContains: "atmos.Component",
+		},
+		{
+			name:            "wrapped ErrInvalidComponent chain is broken",
+			inputErr:        errors.Join(errors.New("outer"), errUtils.ErrInvalidComponent),
+			wantErrDescribe: true,
+			wantErrInvalid:  false, // Chain should be broken
+			wantMsgContains: "failed to describe component",
+		},
```
Comment (osterman) [inline internal/exec/template_funcs_component_test.go]: Wrapping preserves causality (a single chain). errors.Join preserves multiple underlying errors, but it doesn’t express “this happened because of that” the way wrapping does.

File: website/blog/2025-12-15-base-path-behavior-change.md [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+base_path: ""
+base_path: "."
+```
+
+**After (v1.202.0+):**
+```yaml
+# Triggers git root discovery with fallback
+base_path: ""
+
+# Explicitly uses config file directory
```
Comment (osterman) [inline website/blog/2025-12-15-base-path-behavior-change.md]:
```suggestion
# Explicitly uses config file directory relative to the location of the `atmos.yaml`
```
